---
title: "221220 - Database"
output: html_document
date: "2022-12-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

# Input

```{r}
#Libraries
library(pacman)
p_load(tidyverse, janitor, here, haven, labelled, sjmisc, skimr,
       stargazer, purr, conflicted, biclust)

#devtools::install_github("DiogoFerrari/occupar")
library(occupar)

```

```{r}
#Packages conflicts
conflict_prefer("select", "dplyr")
conflict_prefer("filter", "dplyr")
conflict_prefer("lag", "dplyr")

options(max.print=999999)
options(scipen=999)
```

## ISSP Social Inequality 2019

```{r}
#Load database
issp_2019_original = read_dta(here("Input", "issp_social_inequality_2019", "ZA7600_v3-0-0.dta"))  %>% 
  clean_names()

```

# Processing

## Complete database

```{r}
#Select
issp_2019 = issp_2019_original %>% 
  filter(country==380) %>% 
  select(studyno:educyrs, degree:union, isco08, it_inc, caseid:partials)

#Rename
issp_2019 = issp_2019 %>% 
  rename(ib_weafam = v1,
          ib_edupar = v2,
          ib_edu = v3,
          ib_work = v4,
          ib_people = v5,
          ib_pol = v6,
          ib_bribes = v7,
          ib_race = v8,
          ib_relig = v9,
          ib_sex = v10,
          ineq_per = v21,
          red_pub = v22,
          red_pri = v24,
          ineq_jud = v50,
          red_unca = v26,
          red_unsu = v27,
          tax_bel = v28,
          tax_per = v29,
          ineq_ang = v32,
          pay_resp = v44,
          pay_educ = v45,
          pay_need = v46,
          pay_merit = v47)

#Reorder
issp_2019 = issp_2019 %>% 
  select(starts_with("ib_"),
         starts_with("ineq_"),
         starts_with("red_"),
         starts_with("tax_"),
         starts_with("pay_"),
         everything())

```


```{r}
#Missing values and inverting polarity
issp_2019 = issp_2019 %>% 
  mutate(across(ib_weafam:pay_merit, ~replace(., .<0 , NA)),
         across(c(it_inc, educyrs, isco08, emprel, nsup, v61, v41, v42), ~replace(., .<0 , NA)),
         across(ib_weafam:ib_sex,  ~ 6 - .),
         across(c(ineq_per, red_pub, red_pri, red_unca, tax_bel),  ~ 6 - .),
         across(pay_resp:pay_merit,  ~ 6 - .))


#Reorder
issp_2019 = issp_2019 %>% 
  select(starts_with("ib_"),
         starts_with("ineq_"),
         starts_with("red_"),
         starts_with("tax_"),
         starts_with("pay_"),
         everything())

```


## Attitudes towards inequality database

```{r}

#Select and listwise
ITA_net = issp_2019 %>% 
  select(starts_with("ib_"),
         starts_with("ineq_"),
         starts_with("red_"),
         starts_with("tax_"),
         starts_with("pay_")) %>% 
  na.omit()

names(ITA_net)

```

## Networks for NCTs (H2)

### Income

```{r}

#Select and listwise
ITA_income = issp_2019 %>% 
  select(ib_weafam:pay_merit,
         it_inc) %>% 
  rename(income_h = it_inc) %>% 
  na.omit()

#Dummy
ITA_income = ITA_income %>% 
  mutate(income_h = ifelse(income_h<=1875, 0, 1)) #2.000 EUR

#Split
ITA_income = ITA_income %>% 
  group_split(income_h, .keep = FALSE)

income_0 = ITA_income[[1]]
income_1 = ITA_income[[2]]
```


### Education

```{r}

#Select and listwise
ITA_educyrs = issp_2019 %>% 
  select(ib_weafam:pay_merit,
         educyrs) %>% 
  na.omit()

#Dummy
ITA_educyrs = ITA_educyrs %>% 
    mutate(educyrs = ifelse(educyrs<=12, 0, 1)) #12 years (Incomplete secondary)

#Split
ITA_educyrs = ITA_educyrs %>% 
  group_split(educyrs, .keep = FALSE)

edu_0 = ITA_educyrs[[1]]
edu_1 = ITA_educyrs[[2]]
```


### EGP social class

```{r}

#Select and listwise
ITA_egpclass = issp_2019 %>% 
  select(ib_weafam:pay_merit,
         isco08, emprel, nsup)

#ISCO08 - Code (isco08_code)
ITA_egpclass = ITA_egpclass %>% 
  separate(isco08, c("isco08_code", "isco08_label"), remove = FALSE) %>% 
  mutate(isco08_code = as.numeric(paste0(isco08_code)),
         isco08_label = ifelse(is.na(isco08_code), NA, isco08_label))

#Self-employed (self_employed)
ITA_egpclass = ITA_egpclass %>% 
  mutate(self_employed_ = as.numeric(emprel)) %>% 
  mutate(self_employed = case_when(self_employed_==3 ~ 0,
                               self_employed_>=4 & self_employed_<=7 ~ 1,
                               TRUE ~ NA_real_))

#Number of employees (n_employees)
ITA_egpclass = ITA_egpclass %>% 
  mutate(n_employees = ifelse(nsup<0, NA, nsup))

#ISCO08 - ISCO88 - EGP
ITA_egpclass = ITA_egpclass %>% 
  mutate(isco88_code = isco08to88(isco08_code, display.nas = FALSE)) %>% 
  mutate(social_class_3 = isco88toEGP(isco88_code, n.employees=n_employees, self.employed=self_employed, n.classes=3)) 

#Drop IV.c+VII.b  Farm workers 
ITA_egpclass = ITA_egpclass %>% 
  filter(social_class_3!="IV.c+VII.b  Farm workers")


#Select and listwise
ITA_egpclass = ITA_egpclass %>% 
  select(ib_weafam:pay_merit,
         social_class_3) %>% 
  na.omit()

#Dummy
ITA_egpclass_ = ITA_egpclass %>% 
  mutate(social_class_3 = ifelse(
                  social_class_3=="V+VI+VI.a Manual workers", 0, 1)) #V+VI+VI.a Manual workers

#Split
ITA_egpclass = ITA_egpclass_ %>% 
  group_split(social_class_3, .keep = FALSE)

egpclass_0 = ITA_egpclass[[1]]
egpclass_1 = ITA_egpclass[[2]]


```

### Subjective social class

```{r}
#Select and listwise
ITA_subclass = issp_2019 %>% 
  select(ib_weafam:pay_merit,
         v61) %>% 
  rename(subclass = v61) %>% 
  na.omit()

#Dummy
ITA_subclass = ITA_subclass %>% 
  mutate(subclass = ifelse(subclass<=3, 0, 1)) #3. Lower middle class

#Split
ITA_subclass = ITA_subclass %>% 
  group_split(subclass, .keep = FALSE)

subclass_0 = ITA_subclass[[1]]
subclass_1 = ITA_subclass[[2]]
```


### Subjective social mobility

```{r}

#Social mobility
ITA_socmob  = issp_2019
ITA_socmob$socmob = ITA_socmob$v42 - ITA_socmob$v41

#Select and listwise
ITA_socmob = ITA_socmob %>% 
  select(ib_weafam:pay_merit,
         socmob) %>% 
  na.omit()

#Dummy
ITA_socmob = ITA_socmob %>% 
  mutate(socmob = ifelse(socmob>=0, 1, 0)) #0
                 
#Split
ITA_socmob = ITA_socmob %>% 
  group_split(socmob, .keep = FALSE)

socmob_0 = ITA_socmob[[1]]
socmob_1 = ITA_socmob[[2]]
```


## Network for simulation (H3)



```{r}
#Dummies
ITA_net_can = ITA_net %>%
  mutate(across(ib_weafam:pay_merit, ~ ntile(., 2))) %>% 
  mutate(across(ib_weafam:pay_merit, ~ ifelse(.==2, 1, 0)))

#Select variables
ITA_net_can = ITA_net_can %>% 
  select(starts_with("ineq_"),
         starts_with("red_"),
         starts_with("tax_"))

```

## Summary

```{r}
#ITA_net
summary_ITA_net  = ITA_net %>% 
  skim() %>% 
  as.data.frame()

stargazer(as.data.frame(ITA_net), type = "text", nobs = TRUE)

#CAN
summary_can  = as.data.frame(skim(ITA_net_can))
stargazer(as.data.frame(ITA_net_can), type = "text", nobs = TRUE)

```

# Output

```{r}
#ITA_net
write.csv(ITA_net,"../Input/ITA.csv", row.names = FALSE)

#NCTs
dir.create("../Input/NCT")

write.csv(income_0,"../Input/NCT/income0.csv", row.names = FALSE)
write.csv(income_1,"../Input/NCT/income1.csv", row.names = FALSE)

write.csv(edu_0,"../Input/NCT/edu0.csv", row.names = FALSE)
write.csv(edu_1,"../Input/NCT/edu1.csv", row.names = FALSE)

write.csv(egpclass_0,"../Input/NCT/egpclass0.csv", row.names = FALSE)
write.csv(egpclass_1,"../Input/NCT/egpclass1.csv", row.names = FALSE)

write.csv(subclass_0,"../Input/NCT/subclass0.csv", row.names = FALSE)
write.csv(subclass_1,"../Input/NCT/subclass1.csv", row.names = FALSE)

write.csv(socmob_0,"../Input/NCT/socmob0.csv", row.names = FALSE)
write.csv(socmob_1,"../Input/NCT/socmob1.csv", row.names = FALSE)

#CAN
saveRDS(ITA_net_can, here("Input", "ITA_net_can.rds"))
```


