---
title: "221220 - Database"
output: html_document
date: "2022-12-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

# Input

```{r}
#Libraries
library(pacman)
p_load(tidyverse, janitor, here, haven, labelled, sjmisc, skimr,
       stargazer, purr, conflicted, biclust, corclass, poLCA)

```

```{r}
#Packages conflicts
conflict_prefer("select", "dplyr")
conflict_prefer("filter", "dplyr")
conflict_prefer("lag", "dplyr")

options(max.print=999999)
options(scipen=999)
```
## Mijs

```{r}

#Load database
mijs = read_dta(here("Input", "data_full_stata.dta"))  %>% 
  clean_names()

#Select variables
mijs_final = mijs %>% 
  select(nomem_encr, survey, country, treatment, 
         age, sex, race, education, working, politics, pol5, 
         hhincome, immigrant, marital, religion, ladder_present,
         ineq_post1, ineq_post2, ineq_post3, ineq_post4,
         perceived_2_1, perceived_3_1,
         ineq_pre1, ineq_pre2, ineq_pre3,
         belief_1:belief_9,
         ineq_post5, ineq_post6
         )

#Rename
mijs_final = mijs_final %>% 
  rename(ib_weafam = belief_1,
         ib_edupar = belief_2,
         ib_edu = belief_3,
         ib_work = belief_4,
         ib_people = belief_5,
         ib_migra = belief_7,
         ib_race = belief_6, 
         ib_relig = belief_8,
         ib_sex = belief_9)

skim(mijs_final)

#Check variables
mijs_final1 = mijs_final %>% 
  select(-c(nomem_encr, perceived_2_1, perceived_3_1,))

frq(mijs_final1)

#Filter US
mijs_us = mijs_final %>% 
  filter(country==1)

#Databases
#Complete
mijs_us

#Inequality beliefs
mijs_us_ib = mijs_us %>% 
  select(ineq_post1:ineq_post4,
         ineq_pre1:ineq_pre3,
         ib_weafam:ib_sex)

#Save
save(mijs_us, mijs_us_ib,
     file = here("Output",  "230313 - Mijs_Databases.RData"))

#Listwise
# mijs_final1 = mijs_final %>% 
#   na.omit()

#Variables

#Info
#nomem_encr, survey, country, treatment

#Controls
#age, sex, race, education, working, politics, pol5, hhincome, immigrant, marital, religion
#ladder_present

#Perceptions
#ineq_post1, ineq_post2, ineq_post3, ineq_post4 
#perceived_2_1, perceived_3_1

#Beliefs
#ineq_pre1, ineq_pre2, ineq_pre3
#belief_1:belief_9

#Attitudes
#ineq_post5, ineq_post6

frq(mijs_final, perceived_2_1)

```

## ISSP Social Inequality 2019

```{r}
#Load database
issp_2019_original = read_dta(here("Input", "issp_social_inequality_2019", "ZA7600_v3-0-0.dta"))  %>% 
  clean_names()

#Only USA
issp_2019_country = issp_2019_original %>%
    filter(country==840)
```


# Processing

## Main variables

```{r}

#Missing values
issp_2019 = issp_2019_country %>% 
  mutate(across(studyno:partials, ~replace(., .<0 , NA)))

#Rename
issp_2019 = issp_2019 %>% 
  rename(ib_weafam = v1,
          ib_edupar = v2,
          ib_edu = v3,
          ib_work = v4,
          ib_people = v5,
          ib_pol = v6,
          ib_bribes = v7,
          ib_race = v8,
          ib_relig = v9,
          ib_sex = v10,
          ineq_per = v21,
          red_pub = v22,
          red_pri = v24,
          ineq_jud = v50,
          red_unca = v26,
          red_unsu = v27,
          tax_bel = v28,
          tax_per = v29,
          ineq_ang = v32,
          pay_resp = v44,
          pay_educ = v45,
          pay_need = v46,
          pay_merit = v47)

#Reorder
issp_2019 = issp_2019 %>% 
  select(starts_with("ib_"),
         starts_with("ineq_"),
         starts_with("red_"),
         starts_with("tax_"),
         starts_with("pay_"),
         everything())

#Missing values and inverting polarity
issp_2019 = issp_2019 %>% 
  mutate(across(ib_weafam:ib_sex,  ~ 6 - .),
         across(c(ineq_per, red_pub, red_pri, red_unca, tax_bel),  ~ 6 - .),
         across(pay_resp:pay_merit,  ~ 6 - .))

```

## Controls

```{r}

#Gender
issp_2019 = issp_2019 %>% 
  mutate(gender = case_when(sex==1 ~ 0,
                            sex==2 ~ 1))

issp_2019$gender = factor(issp_2019$gender, 
                      levels = c(0:1), 
                      labels = c("Male",
                                 "Female"))
#Age


#Family status
issp_2019 = issp_2019 %>% 
  mutate(married = ifelse(marital <= 2, 1, 0))

issp_2019$married = factor(issp_2019$married, 
                      levels = c(0:1), 
                      labels = c("Non married",
                                 "Married"))

#Employment
issp_2019 = issp_2019 %>% 
  mutate(work_status = case_when(mainstat==3 | mainstat==4 | mainstat==5 | mainstat==6 | 
                                 mainstat==8 | mainstat==9 ~ 0,
                                 mainstat==2 ~ 1,
                                 mainstat==1 | mainstat==7 ~ 2))

issp_2019$work_status = factor(issp_2019$work_status, 
                      levels = c(0:2), 
                      labels = c("Out of workforce",
                                 "Unemployed",
                                 "Employed"))

#Education
issp_2019 = issp_2019 %>% 
  mutate(education_ = as.numeric(degree)) %>% 
  mutate(education = case_when(education_==0 | education_==1 ~ 0,
                               education_==2 ~ 1,
                               education_==3 | education_==4 ~ 2,
                               education_>=5 ~ 3))

issp_2019$education = factor(issp_2019$education, 
                      levels = c(0:3), 
                      labels = c("Primary",
                                 "Lower secondary",
                                 "Upper secondary",
                                 "Tertiary"))


#Zone
issp_2019 = issp_2019 %>% 
  mutate(zone_ = as.numeric(urbrural)) %>%
  mutate(zone = case_when(zone_==1 | zone_==2 ~ 1,
                          zone_>=3 ~ 0))

issp_2019$zone = factor(issp_2019$zone, 
                      levels = c(0:1), 
                      labels = c("Town or rural",
                                 "Big city"))

#Control variables
#frq(issp_2019, gender, age, married, work_status, education, zone)

#Pendant

#Race
#Income

#Databases

#Complete
issp_2019_final = issp_2019 %>% 
  select(caseid, country, c_alphan,
         ib_weafam:ib_sex, 
         ineq_per, red_pub, 
         gender, age, married, work_status, education, zone)

#Inequality beliefs
issp_2019_ib = issp_2019 %>% 
  select(ib_weafam:ib_sex)

#Save
save(issp_2019_final, issp_2019_ib,
     file = here("Output",  "230313 - ISSP_Databases.RData"))

load(here("Output",  "230313 - Databases.RData"))


```



## T-test

```{r}
#loop each V and run t.test
tests_list <- lapply(seq_along(W3_full), function(i){
  t.test(W3_full[[i]], W3_full_nolist[[i]])
})

means = sapply(tests_list, '[[', 'statistic')
pvalues = as.data.frame(sapply(tests_list, '[[', 'p.value')) 
cis = sapply(tests_list, '[[', 'conf.int')

#print true when the means differ
pvalues[,2] = names(W3_full)
pvalues[,3] = with(pvalues,pvalues<0.05)
```


## Summary

```{r}
#ITA_net
summary_ITA_net  = ITA_net %>% 
  skim() %>% 
  as.data.frame()

stargazer(as.data.frame(ITA_net), type = "text", nobs = TRUE)

#CAN
summary_can  = as.data.frame(skim(ITA_net_can))
stargazer(as.data.frame(ITA_net_can), type = "text", nobs = TRUE)

```


