---
title: "221220 - mgm_chile"
output: html_document
date: "2022-12-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Input

```{r message=FALSE, warning=FALSE}
library(pacman)
p_load(tidyverse, janitor, here, haven, labelled, sjmisc, skimr, ggplot2, jtools,
       stargazer, IsingFit, qgraph, Matrix, igraph, NetworkComparisonTest, bootnet,
       rio, IsingSampler, compute.es, foreign, mgm, matrixcalc, openxlsx, RColorBrewer,
       corclass, poLCA, conflicted, EGAnet, texreg)
```

```{r}
#Packages conflicts
conflict_prefer("select", "dplyr")
conflict_prefer("filter", "dplyr")
conflict_prefer("lag", "dplyr")

options(max.print=999999)
options(scipen=999)
```


```{r}
#data US
load(here("Output",  "230313 - Mijs_US_Databases.RData"))

US=mijs_us_ib 

#data NL
load(here("Output",  "230313 - Mijs_NL_Databases.RData"))

NL=mijs_nl_ib 

```


# Processing

## US

### CCA

```{r}
#CCA applied to ISSP US
CCA_group_US <- cca(US, filter.significance = TRUE, filter.value = 0.01, 
                 zero.action = c("ownclass"))  

#preliminary plots
US_plot_CCA_1 = plot(CCA_group_US, 1)
# plot(CCA_group_US, 2)
US_plot_CCA_2 = plot(CCA_group_US, 3)

#their cor matrix
#print(round(CCA_group_US$modules[[1]]$cormat,1))
#print(round(CCA_group_US$modules[[1]]$cormat,2))
#print(round(CCA_group_US$modules[[1]]$cormat,3))
```

```{r}
#add membership to US
US_CCA = US
US_CCA$mem = CCA_group_US$membership

#prepare CCA-driven dataframe for EGA
CCA_US_1 = US_CCA %>% 
  as.data.frame() %>% 
  filter(mem == 1) %>%
  select(perc_income:ib_sex)

CCA_US_2 = US_CCA %>% 
  as.data.frame() %>% 
  filter(mem == 3) %>%
  select(perc_income:ib_sex)

```


### LCA

```{r}
f1 <- as.formula(cbind(perc_income,perc_wealth,perc_poor,perc_black,
                       bel_merit,bel_diversity,bel_equality,ib_weafam,ib_edupar,
                       ib_edu,ib_work,ib_people,ib_race,ib_migra,ib_relig,ib_sex)~1)

#lcas
LCA_US_2 <- poLCA(f1, data=US, nclass=2, maxiter=3000, nrep=5)
LCA_US_3 <- poLCA(f1, data=US, nclass=3, maxiter=3000, nrep=5)
LCA_US_4 <- poLCA(f1, data=US, nclass=4, maxiter=3000, nrep=5)
LCA_US_5 <- poLCA(f1, data=US, nclass=5, maxiter=3000, nrep=5)
LCA_US_6 <- poLCA(f1, data=US, nclass=6, maxiter=3000, nrep=5)
set.seed(123)
LCA_US_7 <- poLCA(f1, data=US, nclass=7, maxiter=3000, nrep=5) #the chosen one
LCA_US_8 <- poLCA(f1, data=US, nclass=8, maxiter=3000, nrep=5)


##plot
jpeg(file = '../Output/7US.jpeg')
 plot(LCA_US_7)
 dev.off()


#comment for LCA6
#1: low perception mid-high individualist and low structuralist
#2: mid high perception high individualist low structuralist
#3: high perception mid high individualist mid low structuralist
#4: mid high perception mid-high individualist and mid low structuralist
#5: super high perception, mid high individualist and mid structuralist
#6: mid high everything
#7: super high evrything

```

```{r}
#add predclass to US and merge
US_CCA$pred = LCA_US_7$predclass
mijs_us$mem = CCA_group_US$membership
mijs_us$pred = LCA_US_7$predclass

#filter out second CCA class
US_CCA = US_CCA %>% 
  filter(mem != 2)
```


### EGA

#### CCA

```{r}
#filter useless v
US_CCA1_EGA = US_CCA %>% 
  filter(mem == 1) %>%
  select(perc_income:ib_sex)

US_CCA2_EGA = US_CCA %>% 
  filter(mem == 3) %>%
  select(perc_income:ib_sex)

US_ega_CCA1<- EGA(data=US_CCA1_EGA,  model = "TMFG", 
                  plot.EGA = TRUE) 

US_ega_CCA2 <- EGA(data=US_CCA2_EGA,  model = "TMFG", 
                  plot.EGA = TRUE) 

```

#### LCA

```{r}
#filter useless v
US_LCA1_EGA = US_CCA %>% 
  filter(pred == 1) %>%
  select(perc_income:ib_sex)

US_LCA2_EGA = US_CCA %>% 
  filter(pred == 2) %>%
  select(perc_income:ib_sex)

US_LCA3_EGA = US_CCA %>% 
  filter(pred == 3) %>%
  select(perc_income:ib_sex)

US_LCA4_EGA = US_CCA %>% 
  filter(pred == 4) %>%
  select(perc_income:ib_sex)

US_LCA5_EGA = US_CCA %>% 
  filter(pred == 5) %>%
  select(perc_income:ib_sex)

US_LCA6_EGA = US_CCA %>% 
  filter(pred == 6) %>%
  select(perc_income:ib_sex)

US_LCA7_EGA = US_CCA %>% 
  filter(pred == 7) %>%
  select(perc_income:ib_sex)



ega_LCA_US_1 <- EGA(data=US_LCA1_EGA,  model = "TMFG", 
                  plot.EGA = TRUE) 

ega_LCA_US_2 <- EGA(data=US_LCA2_EGA,  model = "TMFG", 
                  plot.EGA = TRUE) 

ega_LCA_US_3 <- EGA(data=US_LCA3_EGA,  model = "TMFG", 
                  plot.EGA = TRUE) 

ega_LCA_US_4 <- EGA(data=US_LCA4_EGA,  model = "TMFG", 
                  plot.EGA = TRUE) 

ega_LCA_US_5 <- EGA(data=US_LCA5_EGA,  model = "TMFG", # da problemi
                  plot.EGA = TRUE) 

ega_LCA_US_6 <- EGA(data=US_LCA6_EGA,  model = "TMFG", 
                  plot.EGA = TRUE) 

#ega_LCA_US_7 <- EGA(data=US_LCA7_EGA,  model = "TMFG", 
#                  plot.EGA = TRUE) 

skim(US_LCA7_EGA)
```


## NL

### CCA

```{r}
#CCA applied to ISSP NL
CCA_group_NL <- cca(NL, filter.significance = TRUE, filter.value = 0.01, 
                 zero.action = c("ownclass"))  

#preliminary plots
NL_plot_CCA_1 = plot(CCA_group_NL, 1)
# plot(CCA_group_NL, 2)
NL_plot_CCA_2 = plot(CCA_group_NL, 3)

#their cor matrix
#print(round(CCA_group_NL$modules[[1]]$cormat,1))
#print(round(CCA_group_NL$modules[[1]]$cormat,2))
#print(round(CCA_group_NL$modules[[1]]$cormat,3))
```

```{r}
#add membership to NL
NL_CCA = NL
NL_CCA$mem = CCA_group_NL$membership

#prepare CCA-driven dataframe for EGA
CCA_NL_1 = NL_CCA %>% 
  as.data.frame() %>% 
  filter(mem == 1) %>%
  select(perc_income:ib_sex)

CCA_NL_2 = NL_CCA %>% 
  as.data.frame() %>% 
  filter(mem == 3) %>%
  select(perc_income:ib_sex)

```


### LCA

```{r}
f1 <- as.formula(cbind(perc_income,perc_wealth,perc_poor,perc_black,
                       bel_merit,bel_diversity,bel_equality,ib_weafam,ib_edupar,
                       ib_edu,ib_work,ib_people,ib_race,ib_migra,ib_relig,ib_sex)~1)

#lcas
LCA_NL_2 <- poLCA(f1, data=NL, nclass=2, maxiter=3000, nrep=5)
LCA_NL_3 <- poLCA(f1, data=NL, nclass=3, maxiter=3000, nrep=5)
LCA_NL_4 <- poLCA(f1, data=NL, nclass=4, maxiter=3000, nrep=5)
LCA_NL_5 <- poLCA(f1, data=NL, nclass=5, maxiter=3000, nrep=5)
set.seed(123)
LCA_NL_6 <- poLCA(f1, data=NL, nclass=6, maxiter=3000, nrep=5) #the chosen one
LCA_NL_7 <- poLCA(f1, data=NL, nclass=7, maxiter=3000, nrep=5) 
LCA_NL_8 <- poLCA(f1, data=NL, nclass=8, maxiter=3000, nrep=5)


##plot
 jpeg(file = '../Output/6NL.jpeg')
 plot(LCA_US_7)
 dev.off()

#comment for LCA6
#1: 
#2: 
#3: 
#4: 
#5: 
#6: 
#7: 
```

```{r}
#add predclass to NL and merge
NL_CCA$pred = LCA_NL_6$predclass
mijs_nl$mem = CCA_group_NL$membership
mijs_nl$pred = LCA_NL_6$predclass

#filter out second CCA class
NL_CCA = NL_CCA %>% 
  filter(mem != 2)
```


### EGA

#### CCA

```{r}
#filter useless v
NL_CCA1_EGA = NL_CCA %>% 
  filter(mem == 1) %>%
  select(perc_income:ib_sex)

NL_CCA2_EGA = NL_CCA %>% 
  filter(mem == 3) %>%
  select(perc_income:ib_sex)

NL_ega_CCA1 <- EGA(data=NL_CCA1_EGA,  model = "TMFG", 
                  plot.EGA = TRUE) 

NL_ega_CCA2 <- EGA(data=NL_CCA2_EGA,  model = "TMFG", 
                  plot.EGA = TRUE) 

```

#### LCA

```{r}
#filter useless v
NL_LCA1_EGA = NL_CCA %>% 
  filter(pred == 1) %>%
  select(perc_income:ib_sex)

NL_LCA2_EGA = NL_CCA %>% 
  filter(pred == 2) %>%
  select(perc_income:ib_sex)

NL_LCA3_EGA = NL_CCA %>% 
  filter(pred == 3) %>%
  select(perc_income:ib_sex)

NL_LCA4_EGA = NL_CCA %>% 
  filter(pred == 4) %>%
  select(perc_income:ib_sex)

NL_LCA5_EGA = NL_CCA %>% 
  filter(pred == 5) %>%
  select(perc_income:ib_sex)

NL_LCA6_EGA = NL_CCA %>% 
  filter(pred == 6) %>%
  select(perc_income:ib_sex)




ega_LCA_NL_1 <- EGA(data=NL_LCA1_EGA,  model = "TMFG", 
                  plot.EGA = TRUE) 

ega_LCA_NL_2 <- EGA(data=NL_LCA2_EGA,  model = "TMFG", 
                  plot.EGA = TRUE) 

ega_LCA_NL_3 <- EGA(data=NL_LCA3_EGA,  model = "TMFG", 
                  plot.EGA = TRUE) 

ega_LCA_NL_4 <- EGA(data=NL_LCA4_EGA,  model = "TMFG", 
                  plot.EGA = TRUE) 

ega_LCA_NL_5 <- EGA(data=NL_LCA5_EGA,  model = "TMFG", # da problemi
                  plot.EGA = TRUE) 

ega_LCA_NL_6 <- EGA(data=NL_LCA6_EGA,  model = "TMFG", 
                  plot.EGA = TRUE) 

```

## Cross tab and reg

### US

```{r}
mijs_us = mijs_us %>% 
  rename( CCA = mem, 
          LCA = pred) %>% 
   filter(CCA != 2)

#cross tab
mijs_us %>%
  select(CCA, att_redist) %>%
  flat_table(margin = "row", digits = 1)

#graph
mijs_us_n = nrow(mijs_us)

crosstab_US = mijs_us %>%
  group_by(CCA) %>% 
  mutate(n_cca = n()) %>%
  group_by(CCA, att_redist) %>% 
  summarise(count = n(),
           pct = count / n_cca) %>% 
  slice(1) %>% 
  ggplot(aes(y=pct, x=att_redist)) +
  geom_col() +
  facet_wrap(~CCA) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  scale_x_continuous(breaks = 1:7) +
  labs(x="Attitude towards redistribution", y="Percentage")
ggsave(filename = here("Output", "graph_tab_US.jpg"), plot =  crosstab_US)


#regression
mijs_us = mijs_us %>% 
  mutate(CCA = as.factor(paste0(CCA)),
         hhincome = as.factor(paste0(hhincome)))

m1_US = lm(att_redist ~ CCA, data = mijs_us)
m2_US = lm(att_redist ~ CCA + age + sex + race + education + working + politics + 
        hhincome + immigrant + marital + religion, data = mijs_us)
m3_US = lm(att_redist ~ age + sex + race + education + working + politics + 
        hhincome + immigrant + marital + religion, data = mijs_us)


#xtable
screenreg(list(m1_US, m2_US, m3_US), stars = c(0.01,0.05,0.1))
```


### NL

```{r}
mijs_nl = mijs_nl %>% 
  rename( CCA = mem, 
          LCA = pred) %>% 
   filter(CCA != 2)

#cross tab
mijs_nl %>%
  select(CCA, att_redist) %>%
  flat_table(margin = "row", digits = 1)

#graph
mijs_nl_n = nrow(mijs_nl)

crosstab_NL = mijs_nl %>%
  group_by(CCA) %>% 
  mutate(n_cca = n()) %>%
  group_by(CCA, att_redist) %>% 
  summarise(count = n(),
           pct = count / n_cca) %>% 
  slice(1) %>% 
  ggplot(aes(y=pct, x=att_redist)) +
  geom_col() +
  facet_wrap(~CCA) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  scale_x_continuous(breaks = 1:7) +
  labs(x="Attitude towards redistribution", y="Percentage")
ggsave(filename = here("Output", "graph_tab_NL.jpg"), plot =  crosstab_NL)


#regression
mijs_nl = mijs_nl %>% 
  mutate(CCA = as.factor(paste0(CCA)),
         hhincome = as.factor(paste0(hhincome)))

m1_NL = lm(att_redist ~ CCA, data = mijs_nl)
m2_NL = lm(att_redist ~ CCA + age + sex + race + education + working + politics + 
        hhincome + immigrant + marital + religion, data = mijs_nl)
m3_NL = lm(att_redist ~ age + sex + race + education + working + politics + 
        hhincome + immigrant + marital + religion, data = mijs_nl)


#xtable
screenreg(list(m1_NL, m2_NL, m3_NL), stars = c(0.01,0.05,0.1))
```

# Output

```{r}
save(mijs_us, US_ega_CCA1, US_ega_CCA2, LCA_US_7, CCA_group_US,
     mijs_nl, NL_ega_CCA1, NL_ega_CCA2, LCA_NL_6, CCA_group_NL,
     file = here("Output",  "230314 - Output.RData"))

```

