---
title: "221220 - mgm_chile"
output: html_document
date: "2022-12-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Input

```{r message=FALSE, warning=FALSE}
library(pacman)
p_load(tidyverse, janitor, here, haven, labelled, sjmisc, skimr, ggplot2, jtools,
       stargazer, qgraph, Matrix, igraph, NetworkComparisonTest, bootnet,
       rio, foreign, matrixcalc, corclass, NetworkComparisonTest, conflicted, 
       EGAnet, texreg, ggpubr, lavaan, ltm, kableExtra)
```

```{r}
#Packages conflicts
conflict_prefer("select", "dplyr")
conflict_prefer("filter", "dplyr")
conflict_prefer("lag", "dplyr")
conflict_prefer("igraph", "compose")


options(max.print=999999)
options(scipen=999)
```


```{r}

#Load
rm(list = ls())
load(here("Output",  "230515 - Data_Databases.RData"))

```


# Processing

## Descriptives

### US

```{r}

data_us_skim  = data_us %>% 
  select(starts_with("p_"),
         starts_with("b_"),
         starts_with("ib_"),
         starts_with("att_"),
agegroups, sex, race, education, working, assets, 
        hhincome_groups, immigrant, marital, religion) %>%
  mutate_if(is.character, as.numeric) %>% 
  mutate_if(is.factor, as.numeric) %>% 
  as.data.frame() %>% 
  stargazer(type = "html", 
            out = here("Output","Article","Tables", "Descriptives_us.html"))
```

### NL

```{r}

data_nl_skim  = data_nl %>% 
  select(starts_with("p_"),
         starts_with("b_"),
         starts_with("ib_"),
         starts_with("att_"),
agegroups, sex, race, education, working, assets, 
        hhincome_groups, immigrant, marital, religion) %>% 
  mutate_if(is.character, as.numeric) %>% 
  mutate_if(is.factor, as.numeric) %>% 
  as.data.frame() %>% 
  stargazer(type = "html", 
            out = here("Output","Article","Tables", "Descriptives_nl.html"))
```


## CCA

### US

```{r}

#CCA applied to ISSP US
cca_group_us <- cca(data_us_cca, filter.significance = TRUE, filter.value = 0.01, 
                 zero.action = c("ownclass"))  

#Preliminary plots
us_plot_cca_1 = plot(cca_group_us, 1)
us_plot_cca_3 = plot(cca_group_us, 3)

```

```{r}
#Add membership to US
data_us_cca$cca = cca_group_us$membership
data_us$cca = cca_group_us$membership

#Prepare CCA-driven dataframe for EGA
cca_us_1 = data_us_cca %>% 
  as.data.frame() %>% 
  filter(cca == 1) %>%
  select(p_income:ib_sex)

cca_us_0 = data_us_cca %>% 
  as.data.frame() %>% 
  filter(cca == 3) %>%
  select(p_income:ib_sex)

#Filter out second CCA class
data_us_cca = data_us_cca %>% 
  filter(cca != 2)

#Rename CCA groups
data_us = data_us %>% 
  mutate(cca = ifelse(cca=="1", 1, 0))

data_us_cca = data_us_cca %>% 
  mutate(cca = ifelse(cca=="1", 1, 0))

```

### NL

```{r}

#CCA applied to ISSP NL
cca_group_nl <- cca(data_nl_cca, filter.significance = TRUE, filter.value = 0.01, 
                 zero.action = c("ownclass"))  

#Preliminary plots
nl_plot_cca_1 = plot(cca_group_nl, 1)
nl_plot_cca_3 = plot(cca_group_nl, 3)

```

```{r}
#Add membership to NL
data_nl_cca$cca = cca_group_nl$membership
data_nl$cca = cca_group_nl$membership

#Prepare CCA-driven dataframe for EGA
cca_nl_1 = data_nl_cca %>% 
  as.data.frame() %>% 
  filter(cca == 1) %>%
  select(p_income:ib_sex)

cca_nl_0 = data_nl_cca %>% 
  as.data.frame() %>% 
  filter(cca == 3) %>%
  select(p_income:ib_sex)

#Filter out second CCA class
data_nl_cca = data_nl_cca %>% 
  filter(cca != 2)

#Rename CCA groups

data_nl = data_nl %>% 
  mutate(cca = ifelse(cca=="1", 1, 0))

data_nl_cca = data_nl_cca %>% 
  mutate(cca = ifelse(cca=="1", 1, 0))

```


## EGA

### US

```{r}
#EGA databases
us_cca0_ega = data_us_cca %>% 
  filter(cca == 0) %>%
  select(p_income:ib_sex)

us_cca1_ega = data_us_cca %>% 
  filter(cca == 1) %>%
  select(p_income:ib_sex)

#EGA
ega_us0 <- EGA(data=us_cca0_ega,  model = "TMFG", 
                  plot.EGA = TRUE, 
                  plot.args = list(
                    plot.type = "qgraph",
                    vsize = 15, 
                    alpha = 0.8,
                    legend.position = "none", legend.size = NA,
                    edge.color = c("royalblue", "tomato")))

ega_us1 <- EGA(data=us_cca1_ega,  model = "TMFG", 
                  plot.EGA = TRUE, 
                  plot.args = list(
                    plot.type = "qgraph",
                    vsize = 15, 
                    alpha = 0.8,
                    legend.position = "none", legend.size = NA,
                    edge.color = c("royalblue", "tomato")))
```

### NL

```{r}
#EGA databases
nl_cca0_ega = data_nl_cca %>% 
  filter(cca == 0) %>%
  select(p_income:ib_sex)

nl_cca1_ega = data_nl_cca %>% 
  filter(cca == 1) %>%
  select(p_income:ib_sex)

#EGA
ega_nl0 <- EGA(data=nl_cca0_ega,  model = "TMFG", 
                  plot.EGA = TRUE, 
                  plot.args = list(
                    plot.type = "qgraph",
                    vsize = 15, 
                    alpha = 0.8,
                    legend.position = "none", legend.size = NA,
                    edge.color = c("royalblue", "tomato")))

ega_nl1 <- EGA(data=nl_cca1_ega,  model = "TMFG", 
                  plot.EGA = TRUE, 
                  plot.args = list(
                    plot.type = "qgraph",
                    vsize = 15, 
                    alpha = 0.8,
                    legend.position = "none", legend.size = NA,
                    edge.color = c("royalblue", "tomato")))
```

### Plots

```{r}
#EGA list
list_data_egas <- lapply(ls(pattern="^ega_"), function(x) get(x))
list_data_egas <- list_data_egas[c(3,4,1,2)]
cca_groups = c("US_0", "US_1", "NL_0", "NL_1")

#Compare EGAs
comp_egas = compare.EGA.plots(
  input.list = list_data_egas,
  base.plot = 1,
  labels = cca_groups,
  rows = 2, columns = 2,
  plot.args = list(
    plot.type = "qgraph",
    vsize = 15, 
    alpha = 0.8,
    legend.position = "none", legend.size = NA,
    edge.color = c("royalblue", "tomato"),
    plot.margin = margin(6,6,6,6, "mm")))

#Individual plots
plot_ega_us_0 = comp_egas$individual.plots$`US_0` +
      ggtitle("US 0") +
      theme(plot.title = element_text(size=20, face="bold", hjust = 0.5),
            plot.margin = margin(2,2,2,2, "mm"))

ggsave(here("Output", "Supplemental", "ega_us0.jpg"), 
       plot_ega_us_0, height = 6, width = 6)

plot_ega_us_1 = comp_egas$individual.plots$`US_1` +
      ggtitle("US 1") +
      theme(plot.title = element_text(size=20, face="bold", hjust = 0.5),
            plot.margin = margin(2,2,2,2, "mm"))

ggsave(here("Output", "Supplemental", "ega_us1.jpg"), 
       plot_ega_us_1, height = 6, width = 6)

plot_ega_nl_0 = comp_egas$individual.plots$`NL_0` +
      ggtitle("NL 0") +
      theme(plot.title = element_text(size=20, face="bold", hjust = 0.5),
            plot.margin = margin(2,2,2,2, "mm"))

ggsave(here("Output", "Supplemental", "ega_nl0.jpg"), 
       plot_ega_nl_0, height = 6, width = 6)

plot_ega_nl_1 = comp_egas$individual.plots$`NL_1` +
      ggtitle("NL 1") +
      theme(plot.title = element_text(size=20, face="bold", hjust = 0.5),
            plot.margin = margin(2,2,2,2, "mm"))

ggsave(here("Output", "Supplemental", "ega_nl1.jpg"), 
       plot_ega_nl_1, height = 6, width = 6)


#Full plot
comp_egas_full = comp_egas$comparison.plot

plot_egas <- lapply(ls(pattern="^plot_ega_"), function(x) get(x))
plot_egas <- plot_egas[c(3,4,1,2)]

g_plot_egas = ggarrange(plotlist = plot_egas, ncol = 2, nrow = 2) 


#Save
ggsave(here("Output", "Article", "Graphs", "ega_full.jpg"), 
       g_plot_egas, height = 12, width = 12)

```

### NCT

```{r}

#US
set.seed(1)
nct_us = NCT(cca_us_0, cca_us_1, 
    gamma = 0.5, test.edges = TRUE, edges = "all", 
    test.centrality = TRUE, centrality = "strength")

inputNCTgraph <- ega_us0$network - ega_us1$network
inputNCTgraph[upper.tri(inputNCTgraph)][which(nct_us$einv.pvals$`p-value` >= .05)] <- 0
inputNCTgraph <- forceSymmetric(inputNCTgraph)

pdf(here("Output", "Supplemental", "nct_us.pdf"))
qgraph(inputNCTgraph, 
       #layout = "spring", 
       edge.labels = TRUE, esize = 1)
dev.off()

#NL
set.seed(1)
nct_nl = NCT(cca_nl_0, cca_nl_1, 
    gamma = 0.5, test.edges = TRUE, edges = "all", 
    test.centrality = TRUE, centrality = "strength")

inputNCTgraph <- ega_nl0$network - ega_nl1$network
inputNCTgraph[upper.tri(inputNCTgraph)][which(nct_nl$einv.pvals$`p-value` >= .05)] <- 0
inputNCTgraph <- forceSymmetric(inputNCTgraph)

pdf(here("Output", "Supplemental", "nct_nl.pdf"))
qgraph(inputNCTgraph, 
       #layout = "spring", 
       edge.labels = TRUE, esize = 1)
dev.off()

```



## Sociodemographic Determinants of Inequality Belief Systems

### US

```{r}

#regression
m1_us = glm(cca ~ politics, data = data_us, family=binomial(link="logit"))
m2_us = glm(cca ~ politics + agegroups + sex + race + education + working + assets + 
        hhincome_groups + immigrant + marital + religion, data = data_us, family=binomial(link="logit"))
m3_us = glm(cca ~ agegroups + sex + race + education + working + assets + 
        hhincome_groups + immigrant + marital + religion, data = data_us, family=binomial(link="logit"))

#xtable
stargazer(list(m1_us, m2_us, m3_us), 
          apply.coef = exp,
          apply.se   = exp,
          type = "text", stars = c(0.01,0.05,0.1))

screenreg(list(m1_us, m2_us, m3_us), stars = c(0.01,0.05,0.1))
```

### NL

```{r}
#regression
m1_nl = glm(cca ~ politics, data = data_nl, family=binomial(link="logit"))
m2_nl = glm(cca ~ politics + agegroups + sex + race + education + working + assets + 
        hhincome_groups + immigrant + marital + religion, data = data_nl, family=binomial(link="logit"))
m3_nl = glm(cca ~ agegroups + sex + race + education + working + assets + 
        hhincome_groups + immigrant + marital + religion, data = data_nl, family=binomial(link="logit"))

#xtable
screenreg(list(m1_us, m2_us, m3_us, m1_nl, m2_nl, m3_nl), stars = c(0.01,0.05,0.1),
          file = here("Output", "Article", "Tables", "Sociodemographic_Determinants.doc"))
```



## Inequality Belief Systems and Attitude Towards Redistribution

### Factors

#### US

```{r}
#EGA
data_us_ega = data_us_cca %>% 
  select(p_income:ib_sex)

ega_us_full = EGA(data=data_us_ega,  model = "TMFG") 
ega_us_full$wc

#EFA
efa(data_us_ega, nfactors = 4)

#Factors
data_us = data_us %>% 
    mutate(index_1 = rowMeans(across(c(p_income:p_black,b_diversity,b_equality))),
           index_2 = rowMeans(across(c(ib_weafam, ib_edupar, ib_people))),
           index_3 = rowMeans(across(c(ib_race:ib_sex))))

factor_us1 = data_us_ega %>% 
  select(p_income:p_black,b_diversity,b_equality)

factor_us2 = data_us_ega %>% 
  select(ib_weafam, ib_edupar, ib_people)

factor_us3 = data_us_ega %>% 
  select(ib_race:ib_sex)


#Cronbach
cronbach.alpha(factor_us1, CI=TRUE, standardized=TRUE) #0.858
cronbach.alpha(factor_us2, CI=TRUE, standardized=TRUE) #0.698
cronbach.alpha(factor_us3, CI=TRUE, standardized=TRUE) #0.735


#Factors
data_us = data_us %>% 
  mutate(index_1 = rowMeans(across(c(p_income:p_black,b_diversity,b_equality))),
         index_2 = rowMeans(across(c(ib_weafam, ib_edupar, ib_people))),
         index_3 = rowMeans(across(c(ib_race:ib_sex))))
```




#### NL

```{r}
#EGA
data_nl_ega = data_nl_cca %>% 
  select(p_income:ib_sex)

ega_nl_full = EGA(data=data_nl_ega,  model = "TMFG") 
ega_nl_full$wc

#Factors
data_nl = data_nl %>% 
    mutate(index_1 = rowMeans(across(c(p_income:p_black,b_diversity,b_equality))),
           index_2 = rowMeans(across(c(ib_weafam:ib_people))),
           index_3 = rowMeans(across(c(ib_race:ib_sex))))

factor_nl1 = data_nl_ega %>% 
  select(p_income:p_black,b_diversity,b_equality)

factor_nl2 = data_nl_ega %>% 
  select(ib_weafam:ib_people)

factor_nl3 = data_nl_ega %>% 
  select(ib_race:ib_sex)



#Cronbach
cronbach.alpha(factor_nl1, CI=TRUE, standardized=TRUE) #0.719
cronbach.alpha(factor_nl2, CI=TRUE, standardized=TRUE) #0.713
cronbach.alpha(factor_nl3, CI=TRUE, standardized=TRUE) #0.815

#Factors
data_nl = data_nl %>% 
  mutate(index_1 = rowMeans(across(c(p_income:p_black,b_diversity,b_equality))),
         index_2 = rowMeans(across(c(ib_weafam:ib_people))),
         index_3 = rowMeans(across(c(ib_race:ib_sex))),
         index_4 = as.numeric(b_merit))
```

### Graphs

#### US

```{r}
data_us = data_us %>% 
  rename( cca = cca, 
          #LCA = pred
          ) %>% 
   filter(cca != 2)

#cross tab
data_us %>%
  select(cca, att_redist) %>%
  flat_table(margin = "row", digits = 1)

#graph
data_us_n = nrow(data_us)

crosstab_us = data_us %>%
  group_by(cca) %>% 
  mutate(n_cca = n()) %>%
  group_by(cca, att_redist) %>% 
  summarise(count = n(),
           pct = count / n_cca) %>% 
  slice(1) %>% 
  ggplot(aes(y=pct, x=att_redist)) +
  geom_col() +
  facet_wrap(~cca) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  scale_x_continuous(breaks = 1:7) +
  labs(x="Attitude towards redistribution", y="Percentage")
ggsave(filename = here("Output", "Article", "Graphs", "Histo_us.jpg"), plot =  crosstab_us)
```


#### NL

```{r}
data_nl = data_nl %>% 
  rename( cca = cca, 
          #LCA = pred
          ) %>% 
   filter(cca != 2)

#cross tab
data_nl %>%
  select(cca, att_redist) %>%
  flat_table(margin = "row", digits = 1)

#graph
data_nl_n = nrow(data_nl)

crosstab_nl = data_nl %>%
  group_by(cca) %>% 
  mutate(n_cca = n()) %>%
  group_by(cca, att_redist) %>% 
  summarise(count = n(),
           pct = count / n_cca) %>% 
  slice(1) %>% 
  ggplot(aes(y=pct, x=att_redist)) +
  geom_col() +
  facet_wrap(~cca) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  scale_x_continuous(breaks = 1:7) +
  labs(x="Attitude towards redistribution", y="Percentage")
ggsave(filename = here("Output", "Article", "Graphs", "Histo_nl.jpg"), plot =  crosstab_nl)
```

### Regression

#### US

```{r}
#Regression
m1_us = lm(att_redist ~ cca, data = data_us)
m2_us = lm(att_redist ~ index_1 + index_2 + index_3 + b_merit + ib_work + ib_edu , data = data_us)
m3_us = lm(att_redist ~ cca + index_1 + index_2 + index_3 + b_merit + ib_work + ib_edu, data = data_us)
m4_us = lm(att_redist ~ cca + index_1 + index_2 + index_3 + b_merit + ib_work + ib_edu + 
             age + sex + race + education + working + politics + 
        hhincome_groups + immigrant + marital + religion, data = data_us)


#xtable
screenreg(list(m1_us, m2_us, m3_us, m4_us), stars = c(0.01,0.05,0.1),
          file = here("Output", "Article", "Tables", "Attitude_redist_us.doc"))
```

#### NL

```{r}
#Regression
m1_nl = lm(att_redist ~ cca, data = data_nl)
m2_nl = lm(att_redist ~ index_1 + index_2 + index_3 + index_4 , data = data_nl)
m3_nl = lm(att_redist ~ cca + index_1 + index_2 + index_3 + index_4, data = data_nl)
m4_nl = lm(att_redist ~ cca + index_1 + index_2 + index_3 + index_4 + 
             age + sex + race + education + working + politics + 
        hhincome_groups + immigrant + marital + religion, data = data_nl)


#xtable
screenreg(list(m1_nl, m2_nl, m3_nl, m4_nl), stars = c(0.01,0.05,0.1),
          file = here("Output", "Article", "Tables", "Attitude_redist_nl.doc"))
```

