---
title: "221220 - Database"
output: html_document
date: "2022-12-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

# Input

```{r}
#Libraries
library(pacman)
p_load(tidyverse, janitor, here, haven, labelled, sjmisc, skimr,
       stargazer, purr, conflicted, biclust, corclass, poLCA)

```

```{r}
#Packages conflicts
conflict_prefer("select", "dplyr")
conflict_prefer("filter", "dplyr")
conflict_prefer("lag", "dplyr")
conflict_prefer("to_factor", "labelled")
conflict_prefer("to_character", "labelled")


options(max.print=999999)
options(scipen=999999)
```

# Processing

```{r}
#Load database
mijs = read_dta(here("Input", "data_full_stata.dta"))  %>% 
  clean_names()

#Select variables
mijs_final = mijs %>% 
  select(nomem_encr, survey, country, treatment, 
         age, agegroups, sex, race, education, peducation, 
         working, politics, pol5, 
         hhincome, assets, immigrant, marital, religion, ladder_present,
         ineq_post1, ineq_post2, ineq_post3, ineq_post4,
         ineq_pre1, ineq_pre2, ineq_pre3,
         belief_1:belief_9,
         ineq_post5, ineq_post6
         )

mijs_final = mijs %>%
  rename(ib_weafam = belief_1,
         ib_edupar = belief_2,
         ib_edu = belief_3,
         ib_work = belief_4,
         ib_people = belief_5,
         ib_migra = belief_7,
         ib_race = belief_6, 
         ib_relig = belief_8,
         ib_sex = belief_9,
         perc_income = ineq_post1, 
         perc_wealth = ineq_post2, 
         perc_poor = ineq_post3, 
         perc_black = ineq_post4,
         bel_merit = ineq_pre1, 
         bel_diversity = ineq_pre2, 
         bel_equality = ineq_pre3,
         att_redist = ineq_post5, 
         att_discrim = ineq_post6) %>% 
  select(nomem_encr, survey, country, treatment, 
         age, agegroups, sex, race, education, peducation,
         working, politics, pol5, 
         hhincome, assets, immigrant, marital, religion, ladder_present,
         starts_with("perc_"),
         starts_with("bel_"),
         starts_with("ib_"),
         starts_with("att_"))

#Recode
mijs_final_data = mijs_final %>%
  mutate(agegroups = to_factor(agegroups),
         sex = case_when(sex==1 ~ "Male",
                         sex==2 ~ "Female",
                         TRUE ~ NA),
         race = case_when(race==1 ~ "White",
                          race!=1 ~ "Other"),
         education = case_when(education<=2 ~ "High school or less",
                          education==3 ~ "Some college",
                          education>=4 ~ "College or more"),
         peducation = case_when(peducation<=2 ~ "High school or less",
                          peducation==3 ~ "Some college",
                          peducation>=4 ~ "College or more"),
         hhincome_groups = case_when(hhincome<=15000 ~ "Low",
                                     hhincome>15000 & hhincome<=70000 ~ "Medium",
                                     hhincome>70000 ~ "High",
                                     TRUE ~NA),
         marital = case_when(marital==1 ~ 1,
                             TRUE ~ 0),
         religion = case_when(religion==1 ~ "Protestant",
                              religion==2 ~ "Catholic",
                              religion==5 ~ "None",
                              religion==3 | religion==4 | religion==6 ~ "Other",
                              TRUE ~ NA))

#Levels
mijs_final_data$education <- factor(mijs_final_data$education,
                levels = c("High school or less", "Some college", "College or more"))

mijs_final_data$peducation <- factor(mijs_final_data$peducation,
                levels = c("High school or less", "Some college", "College or more"))

mijs_final_data$hhincome_groups  <- factor(mijs_final_data$hhincome_groups ,
                levels = c("Low", "Medium", "High"))

#Check variables
frq(mijs_final_data, age, agegroups, sex, race, education, peducation,
         working, politics, pol5, 
         hhincome, hhincome_groups, assets, immigrant, marital, religion, ladder_present)

skim(mijs_final_data)

#Drop variable
mijs_final_data = mijs_final_data %>% 
  select(-peducation)

```




## T-test

```{r}

#Filter US
mijs_us = mijs_final %>% 
  filter(country==1) %>% 
  na.omit()

#Filter NL
mijs_nl = mijs_final %>%  
  filter(country==2) %>% 
  na.omit()

frq(mijs_us, treatment)

mijs_us0 = mijs_us %>% 
  filter(treatment==0) %>% 
  select(-c(nomem_encr:treatment))

mijs_us1 = mijs_us %>% 
  filter(treatment==1) %>% 
  select(-c(nomem_encr:treatment))

mijs_us2 = mijs_us %>% 
  filter(treatment==2) %>% 
  select(-c(nomem_encr:treatment))

mijs_us3 = mijs_us %>% 
  filter(treatment==3) %>% 
  select(-c(nomem_encr:treatment))

mijs_nl0 = mijs_nl %>% 
  filter(treatment==0) %>% 
  select(-c(nomem_encr:treatment))

mijs_nl1 = mijs_nl %>% 
  filter(treatment==1) %>% 
  select(-c(nomem_encr:treatment))

mijs_nl2 = mijs_nl %>% 
  filter(treatment==2) %>% 
  select(-c(nomem_encr:treatment))
 
# mijs_nl3 = mijs_nl %>% 
#   filter(treatment==3)

```

### US

```{r}
#loop each V and run t.test
tests_list <- lapply(seq_along(mijs_us0), function(i){
  t.test(mijs_us0[[i]], mijs_us1[[i]])
})

means = sapply(tests_list, '[[', 'estimate')
dif_mean = means[1,] - means[2,]
pvalues = as.data.frame(sapply(tests_list, '[[', 'p.value')) 

#print true when the means differ
pvalues = pvalues %>%
  rename(pvalues = "sapply(tests_list, \"[[\", \"p.value\")") %>%
  bind_cols(names(mijs_us0))

mult_test = 0.05/nrow(pvalues)

pvalues_us01 = pvalues %>%
  rename(variable = "...2")  %>% 
  bind_cols(dif_mean) %>% 
  filter(pvalues<mult_test) %>% 
  rename(dif_mean = "...3") %>% 
  select(variable, dif_mean, pvalues)



#loop each V and run t.test
tests_list <- lapply(seq_along(mijs_us0), function(i){
  t.test(mijs_us0[[i]], mijs_us2[[i]])
})

means = sapply(tests_list, '[[', 'estimate')
dif_mean = means[1,] - means[2,]
pvalues = as.data.frame(sapply(tests_list, '[[', 'p.value')) 

#print true when the means differ
pvalues = pvalues %>%
  rename(pvalues = "sapply(tests_list, \"[[\", \"p.value\")") %>%
  bind_cols(names(mijs_us0))

mult_test = 0.05/nrow(pvalues)

pvalues_us02 = pvalues %>%
  rename(variable = "...2")  %>% 
  bind_cols(dif_mean) %>% 
  filter(pvalues<mult_test) %>% 
  rename(dif_mean = "...3") %>% 
  select(variable, dif_mean, pvalues)


#loop each V and run t.test
tests_list <- lapply(seq_along(mijs_us0), function(i){
  t.test(mijs_us0[[i]], mijs_us3[[i]])
})

means = sapply(tests_list, '[[', 'estimate')
dif_mean = means[1,] - means[2,]
pvalues = as.data.frame(sapply(tests_list, '[[', 'p.value')) 

#print true when the means differ
pvalues = pvalues %>%
  rename(pvalues = "sapply(tests_list, \"[[\", \"p.value\")") %>%
  bind_cols(names(mijs_us0))

mult_test = 0.05/nrow(pvalues)

pvalues_us03 = pvalues %>%
  rename(variable = "...2")  %>% 
  bind_cols(dif_mean) %>% 
  filter(pvalues<mult_test) %>% 
  rename(dif_mean = "...3") %>% 
  select(variable, dif_mean, pvalues)


#loop each V and run t.test
tests_list <- lapply(seq_along(mijs_us1), function(i){
  t.test(mijs_us1[[i]], mijs_us2[[i]])
})

means = sapply(tests_list, '[[', 'estimate')
dif_mean = means[1,] - means[2,]
pvalues = as.data.frame(sapply(tests_list, '[[', 'p.value')) 

#print true when the means differ
pvalues = pvalues %>%
  rename(pvalues = "sapply(tests_list, \"[[\", \"p.value\")") %>%
  bind_cols(names(mijs_us1))

mult_test = 0.05/nrow(pvalues)

pvalues_us12 = pvalues %>%
  rename(variable = "...2")  %>% 
  bind_cols(dif_mean) %>% 
  filter(pvalues<mult_test) %>% 
  rename(dif_mean = "...3") %>% 
  select(variable, dif_mean, pvalues)


#loop each V and run t.test
tests_list <- lapply(seq_along(mijs_us2), function(i){
  t.test(mijs_us2[[i]], mijs_us3[[i]])
})

means = sapply(tests_list, '[[', 'estimate')
dif_mean = means[1,] - means[2,]
pvalues = as.data.frame(sapply(tests_list, '[[', 'p.value')) 

#print true when the means differ
pvalues = pvalues %>%
  rename(pvalues = "sapply(tests_list, \"[[\", \"p.value\")") %>%
  bind_cols(names(mijs_us2))

mult_test = 0.05/nrow(pvalues)

pvalues_us23 = pvalues %>%
  rename(variable = "...2")  %>% 
  bind_cols(dif_mean) %>% 
  filter(pvalues<mult_test) %>% 
  rename(dif_mean = "...3") %>% 
  select(variable, dif_mean, pvalues)

#loop each V and run t.test
tests_list <- lapply(seq_along(mijs_us1), function(i){
  t.test(mijs_us1[[i]], mijs_us3[[i]])
})

means = sapply(tests_list, '[[', 'estimate')
dif_mean = means[1,] - means[2,]
pvalues = as.data.frame(sapply(tests_list, '[[', 'p.value')) 

#print true when the means differ
pvalues = pvalues %>%
  rename(pvalues = "sapply(tests_list, \"[[\", \"p.value\")") %>%
  bind_cols(names(mijs_us1))

mult_test = 0.05/nrow(pvalues)

pvalues_us13 = pvalues %>%
  rename(variable = "...2")  %>% 
  bind_cols(dif_mean) %>% 
  filter(pvalues<mult_test) %>% 
  rename(dif_mean = "...3") %>% 
  select(variable, dif_mean, pvalues)


pvalues_us01
pvalues_us02
pvalues_us03
pvalues_us12
pvalues_us13
pvalues_us23
```

### NL

```{r}
#loop each V and run t.test
tests_list <- lapply(seq_along(mijs_nl0), function(i){
  t.test(mijs_nl0[[i]], mijs_nl1[[i]])
})

means = sapply(tests_list, '[[', 'estimate')
dif_mean = means[1,] - means[2,]
pvalues = as.data.frame(sapply(tests_list, '[[', 'p.value')) 

#print true when the means differ
pvalues = pvalues %>%
  rename(pvalues = "sapply(tests_list, \"[[\", \"p.value\")") %>%
  bind_cols(names(mijs_nl0))

mult_test = 0.05/nrow(pvalues)

pvalues_nl01 = pvalues %>%
  rename(variable = "...2")  %>% 
  bind_cols(dif_mean) %>% 
  filter(pvalues<mult_test) %>% 
  rename(dif_mean = "...3") %>% 
  select(variable, dif_mean, pvalues)



#loop each V and run t.test
tests_list <- lapply(seq_along(mijs_nl0), function(i){
  t.test(mijs_nl0[[i]], mijs_nl2[[i]])
})

means = sapply(tests_list, '[[', 'estimate')
dif_mean = means[1,] - means[2,]
pvalues = as.data.frame(sapply(tests_list, '[[', 'p.value')) 

#print true when the means differ
pvalues = pvalues %>%
  rename(pvalues = "sapply(tests_list, \"[[\", \"p.value\")") %>%
  bind_cols(names(mijs_nl0))

mult_test = 0.05/nrow(pvalues)

pvalues_nl02 = pvalues %>%
  rename(variable = "...2")  %>% 
  bind_cols(dif_mean) %>% 
  filter(pvalues<mult_test) %>% 
  rename(dif_mean = "...3") %>% 
  select(variable, dif_mean, pvalues)


#loop each V and run t.test
tests_list <- lapply(seq_along(mijs_nl1), function(i){
  t.test(mijs_nl1[[i]], mijs_nl2[[i]])
})

means = sapply(tests_list, '[[', 'estimate')
dif_mean = means[1,] - means[2,]
pvalues = as.data.frame(sapply(tests_list, '[[', 'p.value')) 

#print true when the means differ
pvalues = pvalues %>%
  rename(pvalues = "sapply(tests_list, \"[[\", \"p.value\")") %>%
  bind_cols(names(mijs_nl1))

mult_test = 0.05/nrow(pvalues)

pvalues_nl12 = pvalues %>%
  rename(variable = "...2")  %>% 
  bind_cols(dif_mean) %>% 
  filter(pvalues<mult_test) %>% 
  rename(dif_mean = "...3") %>% 
  select(variable, dif_mean, pvalues)


pvalues_nl01
pvalues_nl02
pvalues_nl12
```


## T-test (NEW)

```{r}

#Filter US
mijs_us = mijs_final %>% 
  filter(country==1) %>% 
  na.omit()

#Filter NL
mijs_nl = mijs_final %>%  
  filter(country==2) %>% 
  na.omit()


mijs_us_yes1 = mijs_us %>% 
  select(-c(nomem_encr:treatment))

mijs_us_not1 = mijs_us %>% 
  filter(treatment!=1) %>% 
  select(-c(nomem_encr:treatment))

mijs_nl_yes1 = mijs_nl %>% 
  select(-c(nomem_encr:treatment))

mijs_nl_not1 = mijs_nl %>% 
  filter(treatment!=1) %>% 
  select(-c(nomem_encr:treatment))

```

### US

```{r}
#loop each V and run t.test
tests_list <- lapply(seq_along(mijs_us_yes1), function(i){
  t.test(mijs_us_yes1[[i]], mijs_us_not1[[i]])
})

means = sapply(tests_list, '[[', 'estimate')
dif_mean = means[1,] - means[2,]
pvalues = as.data.frame(sapply(tests_list, '[[', 'p.value')) 

#print true when the means differ
pvalues = pvalues %>%
  rename(pvalues = "sapply(tests_list, \"[[\", \"p.value\")") %>%
  bind_cols(names(mijs_us0))

mult_test = 0.05/nrow(pvalues)

pvalues_us_01 = pvalues %>%
  rename(variable = "...2")  %>% 
  bind_cols(dif_mean) %>% 
  #filter(pvalues<mult_test) %>% 
  rename(dif_mean = "...3") %>% 
  select(variable, dif_mean, pvalues)

pvalues_us_01
```


### NL

```{r}
#loop each V and run t.test
tests_list <- lapply(seq_along(mijs_nl_yes1), function(i){
  t.test(mijs_nl_yes1[[i]], mijs_nl_not1[[i]])
})

means = sapply(tests_list, '[[', 'estimate')
dif_mean = means[1,] - means[2,]
pvalues = as.data.frame(sapply(tests_list, '[[', 'p.value')) 

#print true when the means differ
pvalues = pvalues %>%
  rename(pvalues = "sapply(tests_list, \"[[\", \"p.value\")") %>%
  bind_cols(names(mijs_nl0))

mult_test = 0.05/nrow(pvalues)

pvalues_nl_01 = pvalues %>%
  rename(variable = "...2")  %>% 
  bind_cols(dif_mean) %>% 
  # filter(pvalues<mult_test) %>% 
  rename(dif_mean = "...3") %>% 
  select(variable, dif_mean, pvalues)

pvalues_nl_01
```

## Summary

```{r}
#Filter US
mijs_us = mijs_final_data %>% 
  filter(country==1) %>% 
  na.omit()

#Filter NL
mijs_nl = mijs_final_data %>% 
  filter(country==2) %>% 
  na.omit()

#US
mijs_us_skim  = mijs_us %>% 
  mutate_if(is.character, as.numeric) %>% 
  mutate_if(is.factor, as.numeric) %>% 
  as.data.frame() %>% 
  stargazer(type = "text")

#NL
mijs_nl_skim  = mijs_nl %>% 
  mutate_if(is.character, as.numeric) %>% 
  mutate_if(is.factor, as.numeric) %>% 
  as.data.frame() %>% 
  stargazer(type = "text")
```

# Output

## Database

```{r}


#Databases

#US

#Complete
mijs_us

#Inequality beliefs
mijs_us_ib = mijs_us %>% 
  select(perc_income:ib_sex)

#Save
save(mijs_us, mijs_us_ib,
     file = here("Output",  "230313 - Mijs_US_Databases.RData"))


#NL

#Complete
mijs_nl

#Inequality beliefs
mijs_nl_ib = mijs_nl %>% 
  select(perc_income:ib_sex)


#Save
save(mijs_nl, mijs_nl_ib,
     file = here("Output",  "230313 - Mijs_NL_Databases.RData"))


#Variables

#Info
#nomem_encr, survey, country, treatment

#Controls
#age, sex, race, education, working, politics, pol5, hhincome, immigrant, marital, religion
#ladder_present

#Perceptions
#ineq_post1, ineq_post2, ineq_post3, ineq_post4 
#perceived_2_1, perceived_3_1

#Beliefs
#ineq_pre1, ineq_pre2, ineq_pre3
#belief_1:belief_9

#Attitudes
#ineq_post5, ineq_post6

```

## P-values

```{r}
save(pvalues_us01,pvalues_us02,pvalues_us03,pvalues_us12,
      pvalues_us13,pvalues_us23, pvalues_nl01, pvalues_nl02, pvalues_nl12,
     pvalues_us_01, pvalues_nl_01,
       file = here("Output",  "230314 - pvalues.RData"))
```

