---
title: "221220 - Database"
output: html_document
date: "2022-12-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

# Input

```{r}
#Libraries
library(pacman)
p_load(tidyverse, janitor, here, haven, labelled, sjmisc, skimr,
       stargazer, purr, conflicted, biclust, corclass, poLCA)

```

```{r}
#Packages conflicts
conflict_prefer("select", "dplyr")
conflict_prefer("filter", "dplyr")
conflict_prefer("lag", "dplyr")
conflict_prefer("to_factor", "labelled")
conflict_prefer("to_character", "labelled")


options(max.print=999999)
options(scipen=999999)
```

```{r}
load mijs_final

```


## T-test

```{r}

#Filter US
mijs_us = mijs_final %>% 
  filter(country==1) %>% 
  na.omit()

#Filter NL
mijs_nl = mijs_final %>%  
  filter(country==2) %>% 
  na.omit()

frq(mijs_us, treatment)

mijs_us0 = mijs_us %>% 
  filter(treatment==0) %>% 
  select(-c(nomem_encr:treatment))

mijs_us1 = mijs_us %>% 
  filter(treatment==1) %>% 
  select(-c(nomem_encr:treatment))

mijs_us2 = mijs_us %>% 
  filter(treatment==2) %>% 
  select(-c(nomem_encr:treatment))

mijs_us3 = mijs_us %>% 
  filter(treatment==3) %>% 
  select(-c(nomem_encr:treatment))

mijs_nl0 = mijs_nl %>% 
  filter(treatment==0) %>% 
  select(-c(nomem_encr:treatment))

mijs_nl1 = mijs_nl %>% 
  filter(treatment==1) %>% 
  select(-c(nomem_encr:treatment))

mijs_nl2 = mijs_nl %>% 
  filter(treatment==2) %>% 
  select(-c(nomem_encr:treatment))
 
# mijs_nl3 = mijs_nl %>% 
#   filter(treatment==3)

```

### US

```{r}
#loop each V and run t.test
tests_list <- lapply(seq_along(mijs_us0), function(i){
  t.test(mijs_us0[[i]], mijs_us1[[i]])
})

means = sapply(tests_list, '[[', 'estimate')
dif_mean = means[1,] - means[2,]
pvalues = as.data.frame(sapply(tests_list, '[[', 'p.value')) 

#print true when the means differ
pvalues = pvalues %>%
  rename(pvalues = "sapply(tests_list, \"[[\", \"p.value\")") %>%
  bind_cols(names(mijs_us0))

mult_test = 0.05/nrow(pvalues)

pvalues_us01 = pvalues %>%
  rename(variable = "...2")  %>% 
  bind_cols(dif_mean) %>% 
  filter(pvalues<mult_test) %>% 
  rename(dif_mean = "...3") %>% 
  select(variable, dif_mean, pvalues)



#loop each V and run t.test
tests_list <- lapply(seq_along(mijs_us0), function(i){
  t.test(mijs_us0[[i]], mijs_us2[[i]])
})

means = sapply(tests_list, '[[', 'estimate')
dif_mean = means[1,] - means[2,]
pvalues = as.data.frame(sapply(tests_list, '[[', 'p.value')) 

#print true when the means differ
pvalues = pvalues %>%
  rename(pvalues = "sapply(tests_list, \"[[\", \"p.value\")") %>%
  bind_cols(names(mijs_us0))

mult_test = 0.05/nrow(pvalues)

pvalues_us02 = pvalues %>%
  rename(variable = "...2")  %>% 
  bind_cols(dif_mean) %>% 
  filter(pvalues<mult_test) %>% 
  rename(dif_mean = "...3") %>% 
  select(variable, dif_mean, pvalues)


#loop each V and run t.test
tests_list <- lapply(seq_along(mijs_us0), function(i){
  t.test(mijs_us0[[i]], mijs_us3[[i]])
})

means = sapply(tests_list, '[[', 'estimate')
dif_mean = means[1,] - means[2,]
pvalues = as.data.frame(sapply(tests_list, '[[', 'p.value')) 

#print true when the means differ
pvalues = pvalues %>%
  rename(pvalues = "sapply(tests_list, \"[[\", \"p.value\")") %>%
  bind_cols(names(mijs_us0))

mult_test = 0.05/nrow(pvalues)

pvalues_us03 = pvalues %>%
  rename(variable = "...2")  %>% 
  bind_cols(dif_mean) %>% 
  filter(pvalues<mult_test) %>% 
  rename(dif_mean = "...3") %>% 
  select(variable, dif_mean, pvalues)


#loop each V and run t.test
tests_list <- lapply(seq_along(mijs_us1), function(i){
  t.test(mijs_us1[[i]], mijs_us2[[i]])
})

means = sapply(tests_list, '[[', 'estimate')
dif_mean = means[1,] - means[2,]
pvalues = as.data.frame(sapply(tests_list, '[[', 'p.value')) 

#print true when the means differ
pvalues = pvalues %>%
  rename(pvalues = "sapply(tests_list, \"[[\", \"p.value\")") %>%
  bind_cols(names(mijs_us1))

mult_test = 0.05/nrow(pvalues)

pvalues_us12 = pvalues %>%
  rename(variable = "...2")  %>% 
  bind_cols(dif_mean) %>% 
  filter(pvalues<mult_test) %>% 
  rename(dif_mean = "...3") %>% 
  select(variable, dif_mean, pvalues)


#loop each V and run t.test
tests_list <- lapply(seq_along(mijs_us2), function(i){
  t.test(mijs_us2[[i]], mijs_us3[[i]])
})

means = sapply(tests_list, '[[', 'estimate')
dif_mean = means[1,] - means[2,]
pvalues = as.data.frame(sapply(tests_list, '[[', 'p.value')) 

#print true when the means differ
pvalues = pvalues %>%
  rename(pvalues = "sapply(tests_list, \"[[\", \"p.value\")") %>%
  bind_cols(names(mijs_us2))

mult_test = 0.05/nrow(pvalues)

pvalues_us23 = pvalues %>%
  rename(variable = "...2")  %>% 
  bind_cols(dif_mean) %>% 
  filter(pvalues<mult_test) %>% 
  rename(dif_mean = "...3") %>% 
  select(variable, dif_mean, pvalues)

#loop each V and run t.test
tests_list <- lapply(seq_along(mijs_us1), function(i){
  t.test(mijs_us1[[i]], mijs_us3[[i]])
})

means = sapply(tests_list, '[[', 'estimate')
dif_mean = means[1,] - means[2,]
pvalues = as.data.frame(sapply(tests_list, '[[', 'p.value')) 

#print true when the means differ
pvalues = pvalues %>%
  rename(pvalues = "sapply(tests_list, \"[[\", \"p.value\")") %>%
  bind_cols(names(mijs_us1))

mult_test = 0.05/nrow(pvalues)

pvalues_us13 = pvalues %>%
  rename(variable = "...2")  %>% 
  bind_cols(dif_mean) %>% 
  filter(pvalues<mult_test) %>% 
  rename(dif_mean = "...3") %>% 
  select(variable, dif_mean, pvalues)


pvalues_us01
pvalues_us02
pvalues_us03
pvalues_us12
pvalues_us13
pvalues_us23
```

### NL

```{r}
#loop each V and run t.test
tests_list <- lapply(seq_along(mijs_nl0), function(i){
  t.test(mijs_nl0[[i]], mijs_nl1[[i]])
})

means = sapply(tests_list, '[[', 'estimate')
dif_mean = means[1,] - means[2,]
pvalues = as.data.frame(sapply(tests_list, '[[', 'p.value')) 

#print true when the means differ
pvalues = pvalues %>%
  rename(pvalues = "sapply(tests_list, \"[[\", \"p.value\")") %>%
  bind_cols(names(mijs_nl0))

mult_test = 0.05/nrow(pvalues)

pvalues_nl01 = pvalues %>%
  rename(variable = "...2")  %>% 
  bind_cols(dif_mean) %>% 
  filter(pvalues<mult_test) %>% 
  rename(dif_mean = "...3") %>% 
  select(variable, dif_mean, pvalues)



#loop each V and run t.test
tests_list <- lapply(seq_along(mijs_nl0), function(i){
  t.test(mijs_nl0[[i]], mijs_nl2[[i]])
})

means = sapply(tests_list, '[[', 'estimate')
dif_mean = means[1,] - means[2,]
pvalues = as.data.frame(sapply(tests_list, '[[', 'p.value')) 

#print true when the means differ
pvalues = pvalues %>%
  rename(pvalues = "sapply(tests_list, \"[[\", \"p.value\")") %>%
  bind_cols(names(mijs_nl0))

mult_test = 0.05/nrow(pvalues)

pvalues_nl02 = pvalues %>%
  rename(variable = "...2")  %>% 
  bind_cols(dif_mean) %>% 
  filter(pvalues<mult_test) %>% 
  rename(dif_mean = "...3") %>% 
  select(variable, dif_mean, pvalues)


#loop each V and run t.test
tests_list <- lapply(seq_along(mijs_nl1), function(i){
  t.test(mijs_nl1[[i]], mijs_nl2[[i]])
})

means = sapply(tests_list, '[[', 'estimate')
dif_mean = means[1,] - means[2,]
pvalues = as.data.frame(sapply(tests_list, '[[', 'p.value')) 

#print true when the means differ
pvalues = pvalues %>%
  rename(pvalues = "sapply(tests_list, \"[[\", \"p.value\")") %>%
  bind_cols(names(mijs_nl1))

mult_test = 0.05/nrow(pvalues)

pvalues_nl12 = pvalues %>%
  rename(variable = "...2")  %>% 
  bind_cols(dif_mean) %>% 
  filter(pvalues<mult_test) %>% 
  rename(dif_mean = "...3") %>% 
  select(variable, dif_mean, pvalues)


pvalues_nl01
pvalues_nl02
pvalues_nl12
```


## T-test (NEW)

```{r}

#Filter US
mijs_us = mijs_final %>% 
  filter(country==1) %>% 
  na.omit()

#Filter NL
mijs_nl = mijs_final %>%  
  filter(country==2) %>% 
  na.omit()


mijs_us_yes1 = mijs_us %>% 
  select(-c(nomem_encr:treatment))

mijs_us_not1 = mijs_us %>% 
  filter(treatment!=1) %>% 
  select(-c(nomem_encr:treatment))

mijs_nl_yes1 = mijs_nl %>% 
  select(-c(nomem_encr:treatment))

mijs_nl_not1 = mijs_nl %>% 
  filter(treatment!=1) %>% 
  select(-c(nomem_encr:treatment))

```

### US

```{r}
#loop each V and run t.test
tests_list <- lapply(seq_along(mijs_us_yes1), function(i){
  t.test(mijs_us_yes1[[i]], mijs_us_not1[[i]])
})

means = sapply(tests_list, '[[', 'estimate')
dif_mean = means[1,] - means[2,]
pvalues = as.data.frame(sapply(tests_list, '[[', 'p.value')) 

#print true when the means differ
pvalues = pvalues %>%
  rename(pvalues = "sapply(tests_list, \"[[\", \"p.value\")") %>%
  bind_cols(names(mijs_us0))

mult_test = 0.05/nrow(pvalues)

pvalues_us_01 = pvalues %>%
  rename(variable = "...2")  %>% 
  bind_cols(dif_mean) %>% 
  #filter(pvalues<mult_test) %>% 
  rename(dif_mean = "...3") %>% 
  select(variable, dif_mean, pvalues)

pvalues_us_01
```


### NL

```{r}
#loop each V and run t.test
tests_list <- lapply(seq_along(mijs_nl_yes1), function(i){
  t.test(mijs_nl_yes1[[i]], mijs_nl_not1[[i]])
})

means = sapply(tests_list, '[[', 'estimate')
dif_mean = means[1,] - means[2,]
pvalues = as.data.frame(sapply(tests_list, '[[', 'p.value')) 

#print true when the means differ
pvalues = pvalues %>%
  rename(pvalues = "sapply(tests_list, \"[[\", \"p.value\")") %>%
  bind_cols(names(mijs_nl0))

mult_test = 0.05/nrow(pvalues)

pvalues_nl_01 = pvalues %>%
  rename(variable = "...2")  %>% 
  bind_cols(dif_mean) %>% 
  # filter(pvalues<mult_test) %>% 
  rename(dif_mean = "...3") %>% 
  select(variable, dif_mean, pvalues)

pvalues_nl_01
```

## P-values

```{r}
save(pvalues_us01,pvalues_us02,pvalues_us03,pvalues_us12,
      pvalues_us13,pvalues_us23, pvalues_nl01, pvalues_nl02, pvalues_nl12,
     pvalues_us_01, pvalues_nl_01,
       file = here("Output",  "230314 - pvalues.RData"))
```



## Rubustness check: Treatments

## US

### Control group database

```{r}
data_us 

#Inequality beliefs
data_us_ib_control = data_us %>% 
  filter(treatment==0) %>% 
  select(perc_income:ib_sex)

```


### CCA

```{r}
#CCA applied to ISSP US
cca_group_us_control <- cca(data_us_ib_control, filter.significance = TRUE, filter.value = 0.01, 
                 zero.action = c("ownclass"))  

#preliminary plots
us_plot_cca_1 = plot(cca_group_us_control, 1)
# plot(cca_group_us, 2)
us_plot_cca_2 = plot(cca_group_us_control, 2)

#their cor matrix
#print(round(cca_group_us$modules[[1]]$cormat,1))
#print(round(cca_group_us$modules[[1]]$cormat,2))
#print(round(cca_group_us$modules[[1]]$cormat,3))
```
### EGA

#### CCA

```{r}

#add membership to US
us_cca_control = data_us_ib_control
us_cca_control$mem = cca_group_us_control$membership

#prepare CCA-driven dataframe for EGA
us_cca_control_1 = us_cca_control %>% 
  filter(mem == 1) %>%
  select(perc_income:ib_sex)

us_cca_control_2 = us_cca_control %>% 
  filter(mem == 2) %>%
  select(perc_income:ib_sex)

#EGA
us_ega_cca1_control<- EGA(data=us_cca_control_1,  model = "TMFG", 
                  plot.EGA = TRUE)  #Only bel_merit change community

us_ega_cca2_control <- EGA(data=us_cca_control_2,  model = "TMFG", 
                  plot.EGA = TRUE) 

```


## NL

### Control group database

```{r}
data_nl 

#Inequality beliefs
data_nl_ib_control = data_nl %>% 
  filter(treatment==0) %>% 
  select(perc_income:ib_sex)

```


### CCA

```{r}
#CCA applied to ISSP NL
cca_group_nl_control <- cca(data_nl_ib_control, filter.significance = TRUE, filter.value = 0.01, 
                 zero.action = c("ownclass"))  

#preliminary plots
nl_plot_cca_1 = plot(cca_group_nl_control, 1)
# plot(cca_group_nl, 2)
nl_plot_cca_2 = plot(cca_group_nl_control, 4)

#their cor matrix
#print(round(cca_group_nl$modules[[1]]$cormat,1))
#print(round(cca_group_nl$modules[[1]]$cormat,2))
#print(round(cca_group_nl$modules[[1]]$cormat,3))
```
### EGA

#### CCA

```{r}

#add membership to NL
nl_cca_control = data_nl_ib_control
nl_cca_control$mem = cca_group_nl_control$membership

#prepare CCA-driven dataframe for EGA
nl_cca_control_1 = nl_cca_control %>% 
  filter(mem == 1) %>%
  select(perc_income:ib_sex)

nl_cca_control_2 = nl_cca_control %>% 
  filter(mem == 4) %>%
  select(perc_income:ib_sex)

#EGA
nl_ega_cca1_control<- EGA(data=nl_cca_control_1,  model = "TMFG", 
                  plot.EGA = TRUE)  

nl_ega_cca2_control <- EGA(data=nl_cca_control_2,  model = "TMFG", 
                  plot.EGA = TRUE) #Only bel_diversity and perc_black in a different cluster, with the other perceptions and beliefs

```



