---
title: "221220 - Database"
output: html_document
date: "2022-12-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

# Input

```{r}
#Libraries
library(pacman)
p_load(tidyverse, janitor, here, haven, labelled, sjmisc, skimr,
       stargazer, purr, conflicted, biclust, corclass, poLCA)

```

```{r}
#Packages conflicts
conflict_prefer("select", "dplyr")
conflict_prefer("filter", "dplyr")
conflict_prefer("lag", "dplyr")
conflict_prefer("to_factor", "labelled")
conflict_prefer("to_character", "labelled")


options(max.print=999999)
options(scipen=999999)
```

```{r}
#Load database
data = read_dta(here("Input", "data_full_stata.dta"))  %>% 
  clean_names()
```


# Processing

```{r}

#Select variables
data_final = data %>% 
  select(nomem_encr, survey, country, treatment, 
         age, agegroups, sex, race, education, peducation, 
         working, politics, pol5, 
         hhincome, assets, immigrant, marital, religion, ladder_present,
         ineq_post1, ineq_post2, ineq_post3, ineq_post4,
         ineq_pre1, ineq_pre2, ineq_pre3,
         belief_1:belief_9,
         ineq_post5, ineq_post6
         )

#Rename variables
data_final = data %>%
  rename(ib_weafam = belief_1,
         ib_edupar = belief_2,
         ib_edu = belief_3,
         ib_work = belief_4,
         ib_people = belief_5,
         ib_migra = belief_7,
         ib_race = belief_6, 
         ib_relig = belief_8,
         ib_sex = belief_9,
         perc_income = ineq_post1, 
         perc_wealth = ineq_post2, 
         perc_poor = ineq_post3, 
         perc_black = ineq_post4,
         bel_merit = ineq_pre1, 
         bel_diversity = ineq_pre2, 
         bel_equality = ineq_pre3,
         att_redist = ineq_post5, 
         att_discrim = ineq_post6) %>% 
  select(nomem_encr, survey, country, treatment, 
         age, agegroups, sex, race, education, peducation,
         working, politics, pol5, 
         hhincome, assets, immigrant, marital, religion, ladder_present,
         starts_with("perc_"),
         starts_with("bel_"),
         starts_with("ib_"),
         starts_with("att_"))

#Recode variables
data_final_data = data_final %>%
  mutate(agegroups = to_factor(agegroups),
         sex = case_when(sex==1 ~ "Male",
                         sex==2 ~ "Female",
                         TRUE ~ NA),
         race = case_when(race==1 ~ "White",
                          race!=1 ~ "Other"),
         education = case_when(education<=2 ~ "High school or less",
                          education==3 ~ "Some college",
                          education>=4 ~ "College or more"),
         peducation = case_when(peducation<=2 ~ "High school or less",
                          peducation==3 ~ "Some college",
                          peducation>=4 ~ "College or more"),
         hhincome_groups = case_when(hhincome<=15000 ~ "Low",
                                     hhincome>15000 & hhincome<=70000 ~ "Medium",
                                     hhincome>70000 ~ "High",
                                     TRUE ~NA),
         marital = case_when(marital==1 ~ 1,
                             TRUE ~ 0),
         religion = case_when(religion==1 ~ "Protestant",
                              religion==2 ~ "Catholic",
                              religion==5 ~ "None",
                              religion==3 | religion==4 | religion==6 ~ "Other",
                              TRUE ~ NA))

#Levels
data_final_data$education <- factor(data_final_data$education,
                levels = c("High school or less", "Some college", "College or more"))

data_final_data$peducation <- factor(data_final_data$peducation,
                levels = c("High school or less", "Some college", "College or more"))

data_final_data$hhincome_groups  <- factor(data_final_data$hhincome_groups ,
                levels = c("Low", "Medium", "High"))

#Drop variable
data_final_data = data_final_data %>% 
  select(-peducation)

#Check variables
skim(data_final_data)

```


# Output

## Database

```{r}
#Databases

#US

#Complete
data_us

#Inequality beliefs
data_us_ib = data_us %>% 
  select(perc_income:ib_sex, att_redist)

#Save
save(data_us, data_us_ib,
     file = here("Output",  "230313 - Data_US_Databases.RData"))


#NL

#Complete
data_nl

#Inequality beliefs
data_nl_ib = data_nl %>% 
  select(perc_income:ib_sex, att_redist)


#Save
save(data_nl, data_nl_ib,
     file = here("Output",  "230313 - Data_NL_Databases.RData"))
```


```{r}
#Variables

#Info
#nomem_encr, survey, country, treatment

#Controls
#age, sex, race, education, working, politics, pol5, hhincome, immigrant, marital, religion
#ladder_present

#Perceptions
#ineq_post1, ineq_post2, ineq_post3, ineq_post4 
#perceived_2_1, perceived_3_1

#Beliefs
#ineq_pre1, ineq_pre2, ineq_pre3
#belief_1:belief_9

#Attitudes
#ineq_post5, ineq_post6

```
