---
title: "Design 1: Inequality Belief Systems and Attitude Towards Redistribution in US and the Netherlands"
author: ""
#date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  prettydoc::html_pretty:
    theme: architect
    fig_caption: yes
    df_print: paged
---

<style>
body {
text-align: justify}
</style>

```{r Setup, message=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(
	message = FALSE,
	warning = FALSE,
	echo = FALSE,
	fig.align="center",
	out.width='\\textwidth'
	)
```


# Input

```{r message=FALSE, warning=FALSE}
library(pacman)
p_load(tidyverse, janitor, here, haven, labelled, sjmisc, skimr, ggplot2, jtools,
       stargazer, qgraph, Matrix, igraph, sna, NetworkComparisonTest, bootnet,
       rio, foreign, matrixcalc, corclass, NetworkComparisonTest, conflicted, 
       EGAnet, texreg, ggpubr, lavaan, ltm, kableExtra, sjPlot, psych, nFactors,
       ggcorrplot, ggeffects)

```

```{r}
#Packages conflicts
conflict_prefer("select", "dplyr")
conflict_prefer("filter", "dplyr")
conflict_prefer("lag", "dplyr")
conflict_prefer("igraph", "compose")
conflict_prefer("igraph", "%s%")



options(max.print=999999)
options(scipen=999)
```


```{r}

#Load
rm(list = ls())
load(here("Output",  "230515 - Data_Databases.RData"))

```

```{r}
labels_data = sjlabelled::get_label(data_us) %>%
  as.data.frame() %>% 
  rownames_to_column(var = "variable") %>% 
  `colnames<-`(c("variable", "label")) %>% 
  slice(19:35)

labels_data %>% 
  kable()
  
```


# Processing

## Descriptives

### US

```{r}

data_us_skim  = data_us %>% 
  select(starts_with("p_"),
         starts_with("b_"),
         starts_with("ib_"),
         starts_with("att_"),
agegroups, sex, race, education, working, assets, 
        hhincome_groups, immigrant, marital, religion) %>%
  mutate_if(is.character, as.numeric) %>% 
  mutate_if(is.factor, as.numeric) %>% 
  as.data.frame() %>% 
  stargazer(type = "text")
```

### NL

```{r}

data_nl_skim  = data_nl %>% 
  select(starts_with("p_"),
         starts_with("b_"),
         starts_with("ib_"),
         starts_with("att_"),
agegroups, sex, race, education, working, assets, 
        hhincome_groups, immigrant, marital, religion) %>% 
  mutate_if(is.character, as.numeric) %>% 
  mutate_if(is.factor, as.numeric) %>% 
  as.data.frame() %>% 
  stargazer(type = "text")

```


## CCA

### US

```{r}

#CCA applied to ISSP US
cca_group_us <- cca(data_us_cca, filter.significance = TRUE, filter.value = 0.01, 
                 zero.action = c("ownclass")) 

#Preliminary plots
us_plot_cca_1 = plot(cca_group_us, 1)
us_plot_cca_2 = plot(cca_group_us, 3)

```

```{r}
#Add membership to US
data_us_cca$cca = cca_group_us$membership
data_us$cca = cca_group_us$membership

#Filter out second CCA class and rename CCA groups
data_us = data_us %>% 
  filter(cca != 2) %>% 
  mutate(cca = ifelse(cca=="3", 1, 2))

data_us_cca = data_us_cca %>% 
  filter(cca != 2) %>% 
  mutate(cca = ifelse(cca=="3", 1, 2))

#Prepare CCA-driven dataframe for EGA
cca_us_1 = data_us_cca %>% 
  as.data.frame() %>% 
  filter(cca == 1) %>%
  select(p_income:ib_sex)

cca_us_2 = data_us_cca %>% 
  as.data.frame() %>% 
  filter(cca == 2) %>%
  select(p_income:ib_sex)

```

### NL

```{r}

#CCA applied to ISSP NL
cca_group_nl <- cca(data_nl_cca, filter.significance = TRUE, filter.value = 0.01, 
                 zero.action = c("ownclass"))  

#Preliminary plots
nl_plot_cca_1 = plot(cca_group_nl, 1)
nl_plot_cca_2 = plot(cca_group_nl, 3)

```

```{r}
#Add membership to NL
data_nl_cca$cca = cca_group_nl$membership
data_nl$cca = cca_group_nl$membership

#Filter out second CCA class and rename CCA groups
data_nl = data_nl %>% 
  filter(cca != 2) %>% 
  mutate(cca = ifelse(cca=="3", 2, 1))

data_nl_cca = data_nl_cca %>% 
  filter(cca != 2) %>% 
  mutate(cca = ifelse(cca=="3", 2, 1))

#Prepare CCA-driven dataframe for EGA
cca_nl_1 = data_nl_cca %>% 
  as.data.frame() %>% 
  filter(cca == 1) %>%
  select(p_income:ib_sex)

cca_nl_2 = data_nl_cca %>% 
  as.data.frame() %>% 
  filter(cca == 2) %>%
  select(p_income:ib_sex)

```



## COR matrix

### US
```{r include=TRUE}
#Cor matrix
corr_us_1 <- round(cor(cca_us_1), 1)
corr_us_2 <- round(cor(cca_us_2), 1)

# Compute a matrix of correlation p-values
p.mat_us_1 <- cor_pmat(cca_us_1)
p.mat_us_2 <- cor_pmat(cca_us_2)

# Visualization
cor_m_us_1 = ggcorrplot(corr_us_1, type = "lower", legend.title	= " ",
     outline.col = "white", colors = c( "red", "white", "blue")) +
  ggtitle("US1") +
  theme(plot.title = element_text(size=20, face="bold", hjust = 0.5),
            plot.margin = margin(2,2,2,2, "mm"),
        axis.text.x = element_text(margin=margin(-2,0,0,0)),  # Order: top, right, bottom, left
        axis.text.y = element_text(margin=margin(0,-2,0,0))) +
  geom_vline(xintercept=1:ncol(corr_us_1)-0.5, colour="white", size=2) +
  geom_hline(yintercept=1:ncol(corr_us_1)-0.5, colour="white", size=2) 

cor_m_us_2 = ggcorrplot(corr_us_2, type = "lower", legend.title	= " ",
     outline.col = "white", colors = c( "red", "white", "blue")) +
  ggtitle("US2") +
  theme(plot.title = element_text(size=20, face="bold", hjust = 0.5),
            plot.margin = margin(2,2,2,2, "mm"),
        axis.text.x = element_text(margin=margin(-2,0,0,0)),  # Order: top, right, bottom, left
        axis.text.y = element_text(margin=margin(0,-2,0,0))) +
  geom_vline(xintercept=1:ncol(corr_us_1)-0.5, colour="white", size=2) +
  geom_hline(yintercept=1:ncol(corr_us_1)-0.5, colour="white", size=2) 

cor_m_us_1
cor_m_us_2
```

### NL
```{r include=TRUE}
#Cor matrix
corr_nl_1 <- round(cor(cca_nl_1), 1)
corr_nl_2 <- round(cor(cca_nl_2), 1)

# Compute a matrix of correlation p-values
p.mat_nl_1 <- cor_pmat(cca_nl_1)
p.mat_nl_2 <- cor_pmat(cca_nl_2)

# Visualization
cor_m_nl_1 = ggcorrplot(corr_nl_1, type = "lower", legend.title	= " ",
     outline.col = "white", colors = c( "red", "white", "blue")) +
  ggtitle("NL1") +
  theme(plot.title = element_text(size=20, face="bold", hjust = 0.5),
            plot.margin = margin(2,2,2,2, "mm"),
        axis.text.x = element_text(margin=margin(-2,0,0,0)),  # Order: top, right, bottom, left
        axis.text.y = element_text(margin=margin(0,-2,0,0))) +
  geom_vline(xintercept=1:ncol(corr_nl_1)-0.5, colour="white", size=2) +
  geom_hline(yintercept=1:ncol(corr_nl_1)-0.5, colour="white", size=2) 

cor_m_nl_2 = ggcorrplot(corr_nl_2, type = "lower", legend.title	= " ",
     outline.col = "white", colors = c( "red", "white", "blue")) +
  ggtitle("NL2") +
  theme(plot.title = element_text(size=20, face="bold", hjust = 0.5),
            plot.margin = margin(2,2,2,2, "mm"),
        axis.text.x = element_text(margin=margin(-2,0,0,0)),  # Order: top, right, bottom, left
        axis.text.y = element_text(margin=margin(0,-2,0,0))) +
  geom_vline(xintercept=1:ncol(corr_nl_2)-0.5, colour="white", size=2) +
  geom_hline(yintercept=1:ncol(corr_nl_2)-0.5, colour="white", size=2) 

cor_m_nl_1
cor_m_nl_2
```


```{r}
#Multiplot
plot_cor <- lapply(ls(pattern="^cor_m_"), function(x) get(x))
plot_cor <- plot_cor[c(3,4,1,2)]

g_plot_cor = ggarrange(plotlist = plot_cor, ncol = 2, nrow = 2) 

#Save
ggsave(here("Output", "Article", "Graphs", "cor_full.jpg"), 
       g_plot_cor, height = 12, width = 12)

```

## EGA

### US

```{r include=FALSE}
#EGA databases
us_cca_1_ega = data_us_cca %>% 
  filter(cca == 1) %>%
  select(p_income:ib_sex)

us_cca_2_ega = data_us_cca %>% 
  filter(cca == 2) %>%
  select(p_income:ib_sex)


#EGA
ega_us_1 <- EGA(data=us_cca_1_ega,  model = "glasso", 
                  plot.EGA = TRUE, 
                  plot.args = list(
                    plot.type = "qgraph",
                    vsize = 15, 
                    alpha = 0.8,
                    legend.position = "none", legend.size = NA,
                    edge.color = c("royalblue", "tomato")))

ega_us_2 <- EGA(data=us_cca_2_ega,  model = "glasso", 
                  plot.EGA = TRUE, 
                  plot.args = list(
                    plot.type = "qgraph",
                    vsize = 15, 
                    alpha = 0.8,
                    legend.position = "none", legend.size = NA,
                    edge.color = c("royalblue", "tomato")))
?EGA
```

### NL

```{r include=FALSE}
#EGA databases
nl_cca_1_ega = data_nl_cca %>% 
  filter(cca == 1) %>%
  select(p_income:ib_sex)

nl_cca_2_ega = data_nl_cca %>% 
  filter(cca == 2) %>%
  select(p_income:ib_sex)

#EGA
ega_nl_1 <- EGA(data=nl_cca_1_ega,  model = "glasso", 
                  plot.EGA = TRUE, 
                  plot.args = list(
                    plot.type = "qgraph",
                    vsize = 15, 
                    alpha = 0.8,
                    legend.position = "none", legend.size = NA,
                    edge.color = c("royalblue", "tomato")))

ega_nl_2 <- EGA(data=nl_cca_2_ega,  model = "glasso", 
                  plot.EGA = TRUE, 
                  plot.args = list(
                    plot.type = "qgraph",
                    vsize = 15, 
                    alpha = 0.8,
                    legend.position = "none", legend.size = NA,
                    edge.color = c("royalblue", "tomato")))
```

### Plots

```{r include=FALSE}
#EGA list
list_data_egas <- lapply(ls(pattern="^ega_"), function(x) get(x))
list_data_egas <- list_data_egas[c(3,4,1,2)]
cca_groups = c("US_1", "US_2", "NL_1", "NL_2")

#Compare EGAs
comp_egas = compare.EGA.plots(
  input.list = list_data_egas,
  base.plot = 1,
  labels = cca_groups,
  rows = 2, columns = 2,
  plot.args = list(
    plot.type = "qgraph",
    vsize = 15, 
    alpha = 0.8,
    legend.position = "none", legend.size = NA,
    edge.color = c("royalblue", "tomato"),
    plot.margin = margin(6,6,6,6, "mm")))

#Individual plots
plot_ega_us_1 = comp_egas$individual.plots$`US_1` +
      ggtitle("US1") +
      theme(plot.title = element_text(size=20, face="bold", hjust = 0.5),
            plot.margin = margin(2,2,2,2, "mm"))

ggsave(here("Output", "Supplemental", "ega_us0.jpg"), 
       plot_ega_us_1, height = 6, width = 6)

plot_ega_us_2 = comp_egas$individual.plots$`US_2` +
      ggtitle("US2") +
      theme(plot.title = element_text(size=20, face="bold", hjust = 0.5),
            plot.margin = margin(2,2,2,2, "mm"))

ggsave(here("Output", "Supplemental", "ega_us1.jpg"), 
       plot_ega_us_2, height = 6, width = 6)

plot_ega_nl_1 = comp_egas$individual.plots$`NL_1` +
      ggtitle("NL1") +
      theme(plot.title = element_text(size=20, face="bold", hjust = 0.5),
            plot.margin = margin(2,2,2,2, "mm"))

ggsave(here("Output", "Supplemental", "ega_nl0.jpg"), 
       plot_ega_nl_1, height = 6, width = 6)

plot_ega_nl_2 = comp_egas$individual.plots$`NL_2` +
      ggtitle("NL2") +
      theme(plot.title = element_text(size=20, face="bold", hjust = 0.5),
            plot.margin = margin(2,2,2,2, "mm"))

ggsave(here("Output", "Supplemental", "ega_nl1.jpg"), 
       plot_ega_nl_2, height = 6, width = 6)


#Full plot
comp_egas_full = comp_egas$comparison.plot

plot_egas <- lapply(ls(pattern="^plot_ega_"), function(x) get(x))
plot_egas <- plot_egas[c(3,4,1,2)]

g_plot_egas = ggarrange(plotlist = plot_egas, ncol = 2, nrow = 2) 


#Save
ggsave(here("Output", "Article", "Graphs", "ega_full.jpg"), 
       g_plot_egas, height = 12, width = 12)

```

```{r}
plot_ega_us_1
plot_ega_us_2
plot_ega_nl_1
plot_ega_nl_2

cor_m_us_1
cor_m_us_2
cor_m_nl_1
cor_m_nl_2
```


### NCT

```{r include=FALSE}

#US
set.seed(1)
nct_us = NCT(cca_us_1, cca_us_2, 
    gamma = 0.5, test.edges = TRUE, edges = "all", 
    test.centrality = TRUE, centrality = "strength")

inputNCTgraph <- ega_us_1$network - ega_us_2$network
inputNCTgraph[upper.tri(inputNCTgraph)][which(nct_us$einv.pvals$`p-value` >= .05)] <- 0
inputNCTgraph <- forceSymmetric(inputNCTgraph)

nct_us_plot = qgraph(inputNCTgraph, 
       #layout = "spring", 
       edge.labels = TRUE)


pdf(here("Output", "Supplemental", "nct_us.pdf"))
nct_us_plot
dev.off()

#NL
set.seed(1)
nct_nl = NCT(cca_nl_1, cca_nl_2, 
    gamma = 0.5, test.edges = TRUE, edges = "all", 
    test.centrality = TRUE, centrality = "strength")

inputNCTgraph <- ega_nl_1$network - ega_nl_2$network
inputNCTgraph[upper.tri(inputNCTgraph)][which(nct_nl$einv.pvals$`p-value` >= .05)] <- 0
inputNCTgraph <- forceSymmetric(inputNCTgraph)

nct_nl_plot = qgraph(inputNCTgraph, 
       #layout = "spring", 
       edge.labels = TRUE)

pdf(here("Output", "Supplemental", "nct_nl.pdf"))
nct_nl_plot
dev.off()

```
#### US

```{r}
plot(nct_us_plot)
```

#### NL

```{r}
plot(nct_nl_plot)
```

## Sociodemographic Determinants of Inequality Belief Systems

### US

```{r}

#Categorical variables
data_us = data_us %>% 
  mutate(cca_n = ifelse(cca==1, 0, 1),
         working = ifelse(working==1, "Yes", "No"),
         immigrant = ifelse(immigrant==1, "Yes", "No"),
         marital = ifelse(marital==1, "Yes", "No"))

#Regressions
m1_us_a = glm(cca_n ~ politics, data = data_us, family=binomial(link="logit"))
m2_us_a = glm(cca_n ~ politics + agegroups + sex + race + education + working + assets +
        hhincome_groups + immigrant + marital + religion, data = data_us, family=binomial(link="logit"))
m3_us_a = glm(cca_n ~ agegroups + sex + race + education + working + assets + 
        hhincome_groups + immigrant + marital + religion, data = data_us, family=binomial(link="logit"))
```

### NL

```{r}

#Categorical variables
data_nl = data_nl %>% 
  mutate(cca_n = ifelse(cca==1, 0, 1),
         working = ifelse(working==1, "Yes", "No"),
         immigrant = ifelse(immigrant==1, "Yes", "No"),
         marital = ifelse(marital==1, "Yes", "No"))

#Regressions
m1_nl_a = glm(cca_n ~ politics, data = data_nl, family=binomial(link="logit"))
m2_nl_a = glm(cca_n ~ politics + agegroups + sex + race + education + working + assets + 
        hhincome_groups + immigrant + marital + religion, data = data_nl, family=binomial(link="logit"))
m3_nl_a = glm(cca_n ~ agegroups + sex + race + education + working + assets + 
        hhincome_groups + immigrant + marital + religion, data = data_nl, family=binomial(link="logit"))
```


```{r}

#Output
tab_model(list(m1_us_a, m2_us_a, m3_us_a, m1_nl_a, m2_nl_a, m3_nl_a),
          show.p = TRUE,
          p.style = "stars",
          p.threshold = c(0.1, 0.05, 0.01),
          dv.labels = c("M1-US", "M2-US", "M3-US", "M1-NL", "M2-NL", "M3-NL"),
          collapse.ci = TRUE,
          show.aic = TRUE,
          #show.reflvl = TRUE,
          title = "Table. Logistic regression models on inequality belief membership - US 1 & NL 1",
          string.pred = " ",
          auto.label = FALSE, 
          file = here("Output", "Article", "Tables", "Sociodemographic_Determinants.html")
)

#Output reduced
tab_model(list(m2_us_a, m2_nl_a),
          show.p = TRUE,
          p.style = "stars",
          p.threshold = c(0.1, 0.05, 0.01),
          dv.labels = c("US", "NL"),
          collapse.ci = TRUE,
          show.aic = TRUE,
          #show.reflvl = TRUE,
          title = "Table. Logistic regression models on inequality belief membership - US 1 & NL 1",
          string.pred = " ",
          auto.label = FALSE, 
          file = here("Output", "Article", "Tables", "Sociodemographic_Determinants_Reduced.html")
)

```

```{r}
ggpredict(m2_us_a)
ggpredict(m2_nl_a)
```



## Inequality Belief Systems and Attitude Towards Redistribution

### Factor analysis

```{r}
#EGA US
data_us_net = data_us %>% 
  select(perc_income:ib_sex)

US_ega = EGA(data=data_us_net,  model = "TMFG", 
                  plot.EGA = TRUE) 

#EGA NL
data_nl_net = data_nl %>% 
  select(perc_income:ib_sex)

NL_ega = EGA(data=data_nl_net,  model = "TMFG", 
                  plot.EGA = TRUE) 

#CFA
data_cfa_us = CFA(US_ega, data_us_net, estimator = "WLSMV")
data_cfa_nl = CFA(NL_ega, data_nl_net, estimator = "WLSMV")


#indexes
data_us = data_us %>% 
    mutate(index_1 = rowMeans(across(c(perc_income:perc_black, bel_diversity, bel_equality))),
           index_2 = rowMeans(across(c(bel_merit, ib_work, ib_race:ib_sex))),
           index_3 = rowMeans(across(c(ib_weafam:ib_edu, ib_people))))


data_nl = data_nl %>% 
    mutate(index_1 = rowMeans(across(c(perc_income:bel_equality))),
           index_2 = rowMeans(across(c(ib_race:ib_sex))),
           index_3 = rowMeans(across(c(ib_weafam:ib_people))))
```


### Graphs

#### US

```{r include=FALSE}

#cross tab
data_us %>%
  select(cca, att_redist) %>%
  flat_table(margin = "row", digits = 1)

#graph
data_us_n = nrow(data_us)

crosstab_us = data_us %>%
  group_by(cca) %>% 
  mutate(n_cca = n()) %>%
  group_by(cca, att_redist) %>% 
  summarise(count = n(),
           pct = count / n_cca) %>% 
  slice(1) %>% 
  ggplot(aes(y=pct, x=att_redist)) +
  geom_col() +
  facet_wrap(~cca) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  scale_x_continuous(breaks = 1:7) +
  labs(x="Attitude towards redistribution", y="Percentage")
# ggsave(filename = here("Output", "Article", "Graphs", "Bar_Graph_Att_Redistribution_US.jpg"), plot =  crosstab_us)
```

```{r}
# crosstab_us
```


#### NL

```{r include=FALSE}

#cross tab
data_nl %>%
  select(cca, att_redist) %>%
  flat_table(margin = "row", digits = 1)

#graph
data_nl_n = nrow(data_nl)

crosstab_nl = data_nl %>%
  group_by(cca) %>% 
  mutate(n_cca = n()) %>%
  group_by(cca, att_redist) %>% 
  summarise(count = n(),
           pct = count / n_cca) %>% 
  slice(1) %>% 
  ggplot(aes(y=pct, x=att_redist)) +
  geom_col() +
  facet_wrap(~cca) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  scale_x_continuous(breaks = 1:7) +
  labs(x="Attitude towards redistribution", y="Percentage")
# ggsave(filename = here("Output", "Article", "Graphs", "Bar_Graph_Att_Redistribution_NL.jpg"), plot =  crosstab_nl)
```

```{r}
# crosstab_nl
```

#### Full

```{r}
#Full database
data_us_nl = data_us %>% 
  bind_rows(data_nl) %>% 
  mutate(country_r = ifelse(country==1, "US", "NL"),
         cca_full = paste0(country_r, cca))

#Table
data_us_nl %>% 
  select(cca_full, att_redist) %>% 
  flat_table(margin = "row", digits = 1)
  
#Graph
data_crosstab_us_nl = data_us_nl %>%
  group_by(cca_full) %>% 
  mutate(n_cca = n()) %>%
  ungroup() %>% 
  group_by(cca_full, att_redist) %>% 
  summarise(count = n(),
           pct = count / n_cca) %>% 
  slice(1)

data_crosstab_us_nl$cca_full <- factor(data_crosstab_us_nl$cca_full,
                         levels = c("US1", "US2", "NL1", "NL2"))

crosstab_us_nl = data_crosstab_us_nl %>%   
  ggplot(aes(y=pct, x=att_redist)) +
  geom_col() +
  facet_wrap(~cca_full) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1),
                     limits = c(0,0.5)) +
  scale_x_continuous(breaks = 1:7) +
  labs(x="Attitude towards redistribution", y="Percentage") +
  theme_nice()


ggsave(filename = here("Output", "Article", "Graphs", "redist_full.jpg"), 
       plot =  crosstab_us_nl)

frq(data_us, cca)
frq(data_nl, cca)

```

```{r}
data_us_nl %>%
  group_by(cca_full) %>% 
  summarise(mean_justicia_ingreso = mean(att_redist)) 
```


### Regressions

##### EGA by country

```{r include=FALSE}
#EGA US
data_us_net = data_us %>% 
  select(p_income:ib_sex)

US_ega = EGA(data=data_us_net,  model = "glasso", 
                  plot.EGA = TRUE) 

#EGA NL
data_nl_net = data_nl %>% 
  select(p_income:ib_sex)

NL_ega = EGA(data=data_nl_net,  model = "glasso", 
                  plot.EGA = TRUE) 

#CFA
data_cfa_us = CFA(US_ega, data_us_net, estimator = "WLSMV")
data_cfa_nl = CFA(NL_ega, data_nl_net, estimator = "WLSMV")


#Indexes
data_us = data_us %>% 
    mutate(index_2 = rowMeans(across(c(p_income, p_wealth, p_poor, p_black, b_diversity, b_equality))),
           index_2 = rowMeans(across(c(b_merit, ib_weafam, ib_edu, ib_edupar, ib_work, ib_people))),
           index_3 = rowMeans(across(c(ib_race, ib_migra, ib_relig, ib_sex))))


data_nl = data_nl %>% 
    mutate(index_2 = rowMeans(across(c(p_income, p_wealth, p_poor, p_black, b_merit, b_diversity, b_equality))),
           index_2 = rowMeans(across(c(ib_weafam, ib_edu, ib_edupar, ib_work, ib_people))),
           index_3 = rowMeans(across(c(ib_race, ib_migra, ib_relig, ib_sex))))

#Databases us
index_1_us = data_us %>% 
  select(p_income, p_wealth, p_poor, p_black, b_diversity, b_equality)

index_2_us = data_us %>% 
  select(b_merit, ib_weafam, ib_edu, ib_edupar, ib_work, ib_people)

index_3_us = data_us %>% 
  select(ib_race, ib_migra, ib_relig, ib_sex)

#Databases nl
index_1_nl = data_us %>% 
  select(p_income, p_wealth, p_poor, p_black, b_merit, b_diversity, b_equality)

index_2_nl = data_us %>% 
  select(ib_weafam, ib_edu, ib_edupar, ib_work, ib_people)

index_3_nl = data_us %>% 
  select(ib_race, ib_migra, ib_relig, ib_sex)
```

##### Indexes


```{r echo=TRUE}

#Indexes
data_us = data_us %>% 
    mutate(index_1 = rowMeans(across(c(p_income, p_wealth, p_poor, p_black, b_diversity, b_equality))),
           index_2 = rowMeans(across(c(b_merit, ib_weafam, ib_edu, ib_edupar, ib_work, ib_people))),
           index_3 = rowMeans(across(c(ib_race, ib_migra, ib_relig, ib_sex))))


data_nl = data_nl %>% 
    mutate(index_1 = rowMeans(across(c(p_income, p_wealth, p_poor, p_black, b_merit, b_diversity, b_equality))),
           index_2 = rowMeans(across(c(ib_weafam, ib_edu, ib_edupar, ib_work, ib_people))),
           index_3 = rowMeans(across(c(ib_race, ib_migra, ib_relig, ib_sex))))

#Cronbach
cronbach.alpha(index_1_us, CI=TRUE, standardized=TRUE) # 0.858
cronbach.alpha(index_2_us, CI=TRUE, standardized=TRUE) # 0.456
cronbach.alpha(index_3_us, CI=TRUE, standardized=TRUE) # 0.735

cronbach.alpha(index_1_nl, CI=TRUE, standardized=TRUE) # 0.761
cronbach.alpha(index_2_nl, CI=TRUE, standardized=TRUE) # 0.512
cronbach.alpha(index_3_nl, CI=TRUE, standardized=TRUE) # 0.735

```

##### Regressions

```{r}

#US
m0_us_b = lm(att_redist ~ cca, data = data_us)
m1_us_b = lm(att_redist ~ index_1 + index_2 + index_3 + agegroups + sex + race + education + working + politics + 
        hhincome_groups + immigrant + marital + religion, data = data_us)
m2_us_b = lm(att_redist ~ index_1 + index_2 + index_3 + cca + agegroups + sex + race + education + working + politics + 
        hhincome_groups + immigrant + marital + religion, data = data_us)

#NL
m0_nl_b = lm(att_redist ~ cca, data = data_nl)
m1_nl_b = lm(att_redist ~ index_1 + index_2 + index_3 + agegroups + sex + race + education + working + politics + 
        hhincome_groups + immigrant + marital + religion, data = data_nl)
m2_nl_b = lm(att_redist ~ index_1 + index_2 + index_3 + cca + agegroups + sex + race + education + working + politics + 
        hhincome_groups + immigrant + marital + religion, data = data_nl)
```


```{r}

#Output
tab_model(list(m0_us_b, m1_us_b, m2_us_b, m0_nl_b, m1_nl_b, m2_nl_b),
          #order.terms = c(1:5, 23, 6:22),
          show.p = TRUE,
          p.style = "stars",
          p.threshold = c(0.1, 0.05, 0.01),
          dv.labels = c("M1-US", "M2-US", "M3-US", "M1-NL", "M2-NL", "M3-NL"),
          collapse.ci = TRUE,
          show.aic = TRUE,
          #show.reflvl = TRUE,
          title = "Table. Linear regression models on attitude towards redistribution - US & NL",
          string.pred = " ",
          auto.label = FALSE, 
          file = here("Output", "Article", "Tables", "Attitude_Redistribution_A.html")
)

# #Output reduced
# tab_model(list(m3_us_b, m3_nl_b),
#           #order.terms = c(1:5, 23, 6:22),
#           show.p = TRUE,
#           p.style = "stars",
#           p.threshold = c(0.1, 0.05, 0.01),
#           dv.labels = c("US", "NL"),
#           collapse.ci = TRUE,
#           show.aic = TRUE,
#           #show.reflvl = TRUE,
#           title = "Table. Linear regression models on attitude towards redistribution - US & NL",
#           string.pred = " ",
#           auto.label = FALSE, 
#           file = here("Output", "Article", "Tables", "Attitude_Redistribution_A_Reduced.html")
# )

```

