---
title: "Article"
author: ""
#date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  prettydoc::html_pretty:
    theme: architect
    fig_caption: yes
    df_print: paged
---

<style>
body {
text-align: justify}
</style>

```{r Setup, message=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(
	message = FALSE,
	warning = FALSE,
	echo = FALSE,
	fig.align="center",
	out.width='\\textwidth'
	)
```


# Input

## Packages 

```{r message=FALSE, warning=FALSE}
library(pacman)
p_load(tidyverse, janitor, here, haven, labelled, sjmisc, skimr, ggplot2, jtools,
       stargazer, qgraph, Matrix, igraph, sna, NetworkComparisonTest, bootnet,
       rio, foreign, matrixcalc, corclass, NetworkToolbox, conflicted, 
       EGAnet, texreg, ggpubr, lavaan, ltm, kableExtra, sjPlot, psych, nFactors,
       ggcorrplot, ggeffects, summarytools)

```

```{r}
#Packages conflicts
conflict_prefer("select", "dplyr")
conflict_prefer("filter", "dplyr")
conflict_prefer("lag", "dplyr")
conflict_prefer("labelled", "to_factor")
conflict_prefer("igraph", "compose")
conflict_prefer("igraph", "%s%")

#Options
options(max.print=999999)
options(scipen=999)
```

## Database

```{r}
#Load database
data = read_dta(here("Input", "data_full_stata.dta"))  %>% 
  clean_names()
```

# Processing

## Variables

```{r}

#Rename variables
data_con = data %>%
  rename(ib_weafam = belief_1,
         ib_edupar = belief_2,
         ib_edu = belief_3,
         ib_work = belief_4,
         ib_people = belief_5,
         ib_migra = belief_7,
         ib_race = belief_6, 
         ib_relig = belief_8,
         ib_sex = belief_9,
         p_income = ineq_post1, 
         p_wealth = ineq_post2, 
         p_poor = ineq_post3, 
         p_black = ineq_post4,
         b_merit = ineq_pre1, 
         b_diversity = ineq_pre2, 
         b_equality = ineq_pre3,
         att_redist = ineq_post5)

#Select variables
data_con = data_con %>%
  select(nomem_encr, survey, country, treatment, 
         age, agegroups, sex, race, education, peducation,
         working, politics, pol5, 
         hhincome, immigrant, marital, religion, ladder_present,
         starts_with("p_"),
         starts_with("b_"),
         starts_with("ib_"),
         starts_with("att_"))

#Recode variables
data_cat = data_con %>%
  mutate(agegroups = labelled::to_factor(agegroups),
         sex = case_when(sex==1 ~ "Male",
                         sex==2 ~ "Female",
                         sex==0 ~ "Other"),
         race = case_when(race==1 ~ "White",
                          race!=1 ~ "Other"),
         education = case_when(education<=2 ~ "High school or less",
                          education==3 ~ "Some college",
                          education>=4 ~ "College or more"),
         peducation = case_when(peducation<=2 ~ "High school or less",
                          peducation==3 ~ "Some college",
                          peducation>=4 ~ "College or more"),
         hhincome_groups = case_when(hhincome<=15000 ~ "Low",
                                     hhincome>15000 & hhincome<=70000 ~ "Medium",
                                     hhincome>70000 ~ "High",
                                     TRUE ~NA),
         marital = case_when(marital==1 ~ 1,
                             TRUE ~ 0),
         religion = case_when(religion==1 ~ "Protestant",
                              religion==2 ~ "Catholic",
                              religion==3 | religion==4 | religion==6 ~ "Other",
                              religion==5 | is.na(religion) ~ "None or not declared"))

#Levels
data_cat$education <- factor(data_cat$education,
                levels = c("High school or less", "Some college", "College or more"))

data_cat$peducation <- factor(data_cat$peducation,
                levels = c("High school or less", "Some college", "College or more"))

data_cat$hhincome_groups  <- factor(data_cat$hhincome_groups ,
                levels = c("Low", "Medium", "High"))

#Drop variable
data_cat = data_cat %>% 
  select(-peducation)

#Check variables
skim(data_cat)
names(data_cat)

```


```{r}

#Filter US
data_us = data_cat %>% 
  filter(country==1) %>% 
  na.omit()

data_us_cca = data_us %>% 
  select(p_income:ib_sex)

#Filter NL
data_nl = data_cat %>% 
  filter(country==2) %>% 
  na.omit()

data_nl_cca = data_nl %>% 
  select(p_income:ib_sex)

```


## CCA

### US

```{r}

#CCA applied to ISSP US
cca_group_us <- cca(data_us_cca, filter.significance = TRUE, filter.value = 0.01, 
                 zero.action = c("ownclass")) 

#Preliminary plots
us_plot_cca_1 = plot(cca_group_us, 1)
us_plot_cca_2 = plot(cca_group_us, 3)

```

```{r}
#Add membership to US
data_us_cca$cca = cca_group_us$membership
data_us$cca = cca_group_us$membership

#Filter out second CCA class and rename CCA groups
data_us = data_us %>% 
  filter(cca == 1 | cca == 3) %>% 
  mutate(cca = ifelse(cca=="3", 1, 2))

data_us_cca = data_us_cca %>% 
  filter(cca == 1 | cca == 3) %>% 
  mutate(cca = ifelse(cca=="3", 1, 2))

#Prepare CCA-driven dataframe for EGA
cca_us_1 = data_us_cca %>% 
  as.data.frame() %>% 
  filter(cca == 1) %>%
  select(p_income:ib_sex)

cca_us_2 = data_us_cca %>% 
  as.data.frame() %>% 
  filter(cca == 2) %>%
  select(p_income:ib_sex)

```

### NL

```{r}

#CCA applied to ISSP NL
cca_group_nl <- cca(data_nl_cca, filter.significance = TRUE, filter.value = 0.01, 
                 zero.action = c("ownclass"))  

#Preliminary plots
nl_plot_cca_1 = plot(cca_group_nl, 1)
nl_plot_cca_2 = plot(cca_group_nl, 4)

```

```{r}
#Add membership to NL
data_nl_cca$cca = cca_group_nl$membership
data_nl$cca = cca_group_nl$membership

#Filter out second CCA class and rename CCA groups
data_nl = data_nl %>% 
  filter(cca == 1 | cca == 4) %>% 
  mutate(cca = ifelse(cca=="4", 2, 1))

data_nl_cca = data_nl_cca %>% 
  filter(cca == 1 | cca == 4) %>% 
  mutate(cca = ifelse(cca=="4", 2, 1))

#Prepare CCA-driven dataframe for EGA
cca_nl_1 = data_nl_cca %>% 
  as.data.frame() %>% 
  filter(cca == 1) %>%
  select(p_income:ib_sex)

cca_nl_2 = data_nl_cca %>% 
  as.data.frame() %>% 
  filter(cca == 2) %>%
  select(p_income:ib_sex)


#Full sample
data_final = data_us %>% 
  bind_rows(data_nl)
  
frq(data, country)
frq(data_final, country)

#Save
save(data_final, data_us, data_us_cca, data_nl, data_nl_cca,
     file = here("Output",  "databases.RData"))

```

## Correlation matrix

### US

```{r include=TRUE}
#Cor matrix
corr_us_1 <- round(cor(cca_us_1), 1)
corr_us_2 <- round(cor(cca_us_2), 1)

# Compute a matrix of correlation p-values
p.mat_us_1 <- cor_pmat(cca_us_1)
p.mat_us_2 <- cor_pmat(cca_us_2)

# Visualization
cor_m_us_1 = ggcorrplot(corr_us_1, type = "lower", legend.title	= " ",
     outline.col = "white", colors = c( "red", "white", "blue")) +
  ggtitle("US1") +
  theme(plot.title = element_text(size=20, hjust = 0),
            plot.margin = margin(2,2,2,2, "mm"),
        axis.text.x = element_text(margin=margin(-2,0,0,0)),  # Order: top, right, bottom, left
        axis.text.y = element_text(margin=margin(0,-2,0,0))) +
  geom_vline(xintercept=1:ncol(corr_us_1)-0.5, colour="white", size=2) +
  geom_hline(yintercept=1:ncol(corr_us_1)-0.5, colour="white", size=2) 

cor_m_us_2 = ggcorrplot(corr_us_2, type = "lower", legend.title	= " ",
     outline.col = "white", colors = c( "red", "white", "blue")) +
  ggtitle("US2") +
  theme(plot.title = element_text(size=20, hjust = 0),
            plot.margin = margin(2,2,2,2, "mm"),
        axis.text.x = element_text(margin=margin(-2,0,0,0)),  # Order: top, right, bottom, left
        axis.text.y = element_text(margin=margin(0,-2,0,0))) +
  geom_vline(xintercept=1:ncol(corr_us_1)-0.5, colour="white", size=2) +
  geom_hline(yintercept=1:ncol(corr_us_1)-0.5, colour="white", size=2) 

cor_m_us_1
cor_m_us_2
```

### NL

```{r include=TRUE}
#Cor matrix
corr_nl_1 <- round(cor(cca_nl_1), 1)
corr_nl_2 <- round(cor(cca_nl_2), 1)

# Compute a matrix of correlation p-values
p.mat_nl_1 <- cor_pmat(cca_nl_1)
p.mat_nl_2 <- cor_pmat(cca_nl_2)

# Visualization
cor_m_nl_1 = ggcorrplot(corr_nl_1, type = "lower", legend.title	= " ",
     outline.col = "white", colors = c( "red", "white", "blue")) +
  ggtitle("NL1") +
  theme(plot.title = element_text(size=20, hjust = 0),
            plot.margin = margin(2,2,2,2, "mm"),
        axis.text.x = element_text(margin=margin(-2,0,0,0)),  # Order: top, right, bottom, left
        axis.text.y = element_text(margin=margin(0,-2,0,0))) +
  geom_vline(xintercept=1:ncol(corr_nl_1)-0.5, colour="white", size=2) +
  geom_hline(yintercept=1:ncol(corr_nl_1)-0.5, colour="white", size=2) 

cor_m_nl_2 = ggcorrplot(corr_nl_2, type = "lower", legend.title	= " ",
     outline.col = "white", colors = c( "red", "white", "blue")) +
  ggtitle("NL2") +
  theme(plot.title = element_text(size=20, hjust = 0),
            plot.margin = margin(2,2,2,2, "mm"),
        axis.text.x = element_text(margin=margin(-2,0,0,0)),  # Order: top, right, bottom, left
        axis.text.y = element_text(margin=margin(0,-2,0,0))) +
  geom_vline(xintercept=1:ncol(corr_nl_2)-0.5, colour="white", size=2) +
  geom_hline(yintercept=1:ncol(corr_nl_2)-0.5, colour="white", size=2) 

cor_m_nl_1
cor_m_nl_2
```


```{r}
#Multiplot
plot_cor <- lapply(ls(pattern="^cor_m_"), function(x) get(x))
plot_cor <- plot_cor[c(3,4,1,2)]

g_plot_cor = ggarrange(plotlist = plot_cor, ncol = 2, nrow = 2) 

#Save
ggsave(here("Output", "Article", "Graphs", "cor_full.jpg"), 
       g_plot_cor, height = 12, width = 12)

```

## EGA

### US

```{r}
#EGA
set.seed(1)
ega_us_1 <- EGA(data=cca_us_1,  model = "glasso", 
                  plot.EGA = TRUE, 
                  plot.args = list(
                    plot.type = "qgraph",
                    vsize = 15, 
                    node.alpha = 0.8,
                    legend.position = "none", legend.size = NA,
                    edge.color = c("royalblue", "tomato")))

set.seed(1)
ega_us_2 <- EGA(data=cca_us_2,  model = "glasso", 
                  plot.EGA = TRUE, 
                  plot.args = list(
                    plot.type = "qgraph",
                    vsize = 15, 
                    node.alpha = 0.8,
                    legend.position = "none", legend.size = NA,
                    edge.color = c("royalblue", "tomato")))

```

### NL

```{r}
#EGA
set.seed(1)
ega_nl_1 <- EGA(data=cca_nl_1,  model = "glasso", 
                  plot.EGA = TRUE, 
                  plot.args = list(
                    plot.type = "qgraph",
                    vsize = 15, 
                    node.alpha = 0.8,
                    legend.position = "none", legend.size = NA,
                    edge.color = c("royalblue", "tomato")))

set.seed(1)
ega_nl_2 <- EGA(data=cca_nl_2,  model = "glasso", 
                  plot.EGA = TRUE, 
                  plot.args = list(
                    plot.type = "qgraph",
                    vsize = 15, 
                    node.alpha = 0.8,
                    legend.position = "none", legend.size = NA,
                    edge.color = c("royalblue", "tomato")))

```

### Plot

```{r}
list_data_egas <- lapply(ls(pattern="^ega_"), function(x) get(x))
list_data_egas <- list_data_egas[c(3,4,1,2)]
cca_groups = c("US1", "US2", "NL1", "NL2")
cca_groups_names = c("US1", 
                     "US2", 
                     "NL1", 
                     "NL2")
```

#### Standardized

```{r}

comp_egas = compare.EGA.plots(
  input.list = list_data_egas,
  base.plot = 1,
  labels = cca_groups_names,
  rows = 2, columns = 2,
  plot.args = list(
    plot.type = "qgraph",
    vsize = 15,
    node.alpha = 0.8,
    #edge.size	= 0.5,
    legend = FALSE,
    legend.position = "none", 
    legend.size = FALSE,
    edge.color = c("royalblue", "tomato"),
    plot.margin = margin(6,6,6,6, "cm")
  ))

#Full plot
comp_egas_full = comp_egas$comparison.plot

plot_egas <- lapply(ls(pattern="^plot_ega_"), function(x) get(x))
plot_egas <- plot_egas[c(3,4,1,2)]

g_plot_egas = ggarrange(plotlist = plot_egas, ncol = 2, nrow = 2) 


#Save
ggsave(here("Output", "Supplemental", "EGA_multi_std.png"), 
       comp_egas$comparison.plot, height = 12, width = 12)

```

#### Non standardized

```{r}

#Common objects
totalgroup_cols <- c("darkorange","purple2","seagreen2")
shortnames = names(cca_us_1)
cca_groups
list_data_egas

#Communities
groups_us1 = list(
 " "=c(1:4,6,7),
 " "=c(5,8:12),
 " "=c(13:16))

groups_us2 = list(
 " "=c(1:7),
 " "=c(9:11),
 " "=c(8,12:16))

groups_nl1 = list(
 " "=c(1:5,6,7),
 " "=c(8:12),
 " "=c(13:16))

groups_nl2 = list(
 " "=c(1:5,6,7),
 " "=c(8:12),
 " "=c(13:16))

png(filename  = here("Output", "Article", "Graphs" ,"EGA_multi_nostd.png"), 
     height = 12, width = 12, units = "cm", res = 1000)
lmat <- matrix(1:4, 2, 2)
lo <- layout(lmat, width = c(1, 1))


# US1	uniformly integrated
plot_us1_freel = qgraph(ega_us_1$network, 
  layout = "spring", theme = "Borkulo", 
  labels = shortnames, label.scale = FALSE,
  cut = 0.04,
  esize = 28, 
  title = "Uniformly integrated (US1)", title.cex = 0.7,
  # edge.color = c("royalblue", "tomato"),
  maximum = 1, vsize=11.0, label.cex=0.4, vTrans = 150,
  groups=groups_us1, color=totalgroup_cols,
  legend = FALSE, borders = FALSE)

# NL1	uniformly compartimentalized
plot_nl1_freel = qgraph(ega_nl_1$network, 
  layout = "spring", theme = "Borkulo", 
  labels = shortnames, label.scale = FALSE, repulsion = 1.1,
  cut = 0.04,
  esize = 28, 
  title = "Uniformly compartimentalized (NL1)", title.cex = 0.7,
  # edge.color = c("royalblue", "tomato"),
  maximum = 1, vsize=11.0, label.cex=0.4, vTrans = 150,
  groups=groups_nl1, color=totalgroup_cols,
  legend = FALSE, borders = FALSE)

# US2	contentiously integrated
plot_us2_freel = qgraph(ega_us_2$network, 
  layout = "spring", theme = "Borkulo", 
  labels = shortnames, label.scale = FALSE,
  cut = 0.04,
  esize = 28, 
  title = "Contentiously integrated (US2)", title.cex = 0.7,
  #edge.color = c("royalblue", "tomato"),
  maximum = 1, vsize=11.0, label.cex=0.4, vTrans = 150,
  groups=groups_us2, color=totalgroup_cols,
  legend = FALSE, borders = FALSE)

# NL2	contentiously compartimentalized
plot_nl2_freel = qgraph(ega_nl_2$network, 
  layout = "spring", theme = "Borkulo", 
  labels = shortnames, label.scale = FALSE, repulsion = 1.1,
  cut = 0.04,
  esize = 28, 
  title = "Contentiously compartimentalized (NL2)", title.cex = 0.7,
  #edge.color = c("royalblue", "tomato"),
  maximum = 1, vsize=11.0, label.cex=0.4, vTrans = 150,
  groups=groups_nl2, color=totalgroup_cols,
  legend = FALSE, borders = FALSE)

# ggtitle("NL2") +
#   theme(plot.title = element_text(size=20, face="bold", hjust = 0.5),
#             plot.margin = margin(2,2,2,2, "mm"),
#         axis.text.x = element_text(margin=margin(-2,0,0,0)),  # Order: top, right, bottom, left
#         axis.text.y = element_text(margin=margin(0,-2,0,0))) 

dev.off()

```


## Sociodemographic Determinants of Inequality Belief Systems

```{r}

### US

#Categorical variables
data_us = data_us %>% 
  mutate(cca_n = ifelse(cca==1, 0, 1),
         working = ifelse(working==1, "Yes", "No"),
         immigrant = ifelse(immigrant==1, "Yes", "No"),
         marital = ifelse(marital==1, "Yes", "No"))

#Regressions
m1_us_a = glm(cca_n ~ politics, data = data_us, family=binomial(link="logit"))
m2_us_a = glm(cca_n ~ sex + agegroups + immigrant + race + 
                education + working + hhincome_groups + marital + 
                politics + religion, data = data_us, family=binomial(link="logit"))
m3_us_a = glm(cca_n ~ sex + agegroups + immigrant + race + 
                education + working + hhincome_groups + marital + 
                religion, 
        data = data_us, family=binomial(link="logit"))
```


```{r}

### NL

#Categorical variables
data_nl = data_nl %>% 
  mutate(cca_n = ifelse(cca==1, 0, 1),
         working = ifelse(working==1, "Yes", "No"),
         immigrant = ifelse(immigrant==1, "Yes", "No"),
         marital = ifelse(marital==1, "Yes", "No"))

#Regressions
m1_nl_a = glm(cca_n ~ politics, data = data_nl, family=binomial(link="logit"))
m2_nl_a = glm(cca_n ~ sex + agegroups + immigrant + race + 
                education + working + hhincome_groups + marital + 
                politics + religion, data = data_nl, family=binomial(link="logit"))
m3_nl_a = glm(cca_n ~ sex + agegroups + immigrant + race + 
                education + working + hhincome_groups + marital + 
                religion, 
        data = data_nl, family=binomial(link="logit"))
```

```{r}

#Output reduced
tab_model(list(m2_us_a, m2_nl_a),
          show.p = TRUE,
          p.style = "stars",
          p.threshold = c(0.1, 0.05, 0.01),
          dv.labels = c("US", "NL"),
          collapse.ci = TRUE,
          show.aic = TRUE,
          #show.reflvl = TRUE,
          title = "Table. Logistic regression models on inequality belief membership - US 2 & NL 2",
          string.pred = " ",
          auto.label = FALSE, 
          file = here("Output", "Article", "Tables", "Sociodemographic_Determinants.html")
)


#Output
tab_model(list(m1_us_a, m2_us_a, m3_us_a, m1_nl_a, m2_nl_a, m3_nl_a),
          show.p = TRUE,
          p.style = "stars",
          p.threshold = c(0.1, 0.05, 0.01),
          dv.labels = c("M1-US", "M2-US", "M3-US", "M1-NL", "M2-NL", "M3-NL"),
          collapse.ci = TRUE,
          show.aic = TRUE,
          #show.reflvl = TRUE,
          title = "Table. Logistic regression models on inequality belief membership - US 2 & NL 2",
          string.pred = " ",
          auto.label = FALSE, 
          file = here("Output", "Article", "Tables", "Sociodemographic_Determinants_Extended.html")
)

```

```{r}
#Predicted values
ggpredict(m2_us_a)
ggpredict(m2_nl_a)

```



## Inequality Belief Systems and Attitude Towards Redistribution

### Graph

```{r}
#Full database
data_final = data_final %>% 
  mutate(country_r = ifelse(country==1, "US", "NL"),
         cca_full = case_when(country==1 & cca==1 ~ "Uniformly integrated (US1)",
                              country==1 & cca==2 ~ "Contentiously integrated (US2)",
                              country==2 & cca==1 ~ "Uniformly compartimentalized (NL1)",
                              country==2 & cca==2 ~ "Contentiously compartimentalized (NL2)"))

#Table
data_final %>% 
  select(cca_full, att_redist) %>% 
  flat_table(margin = "row", digits = 1)
  
#Graph
data_crosstab_us_nl = data_final %>%
  group_by(cca_full) %>% 
  mutate(n_cca = n()) %>%
  ungroup() %>% 
  group_by(cca_full, att_redist) %>% 
  summarise(count = n(),
           pct = count / n_cca) %>% 
  slice(1)

data_crosstab_us_nl$cca_full <- factor(data_crosstab_us_nl$cca_full,
                         levels = c("Uniformly integrated (US1)", 
                                    "Contentiously integrated (US2)", 
                                    "Uniformly compartimentalized (NL1)", 
                                    "Contentiously compartimentalized (NL2)"))

crosstab_us_nl = data_crosstab_us_nl %>%   
  ggplot(aes(y=pct, x=att_redist)) +
  geom_col() +
  facet_wrap(~cca_full) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1),
                     limits = c(0,0.5)) +
  scale_x_continuous(breaks = 1:7) +
  labs(x="Attitude towards redistribution", y="Percentage") +
  theme_bw()


ggsave(filename = here("Output", "Article", "Graphs", "redist_full.jpg"), 
       plot =  crosstab_us_nl)

```

```{r}
data_final %>%
  group_by(cca_full) %>% 
  summarise(mean_justicia_ingreso = mean(att_redist)) 
```

### Regressions

```{r}
#EGA US
data_us_net = data_us %>% 
  select(p_income:ib_sex)

set.seed(1)
US_ega = EGA(data=data_us_net,  model = "glasso", 
                  plot.EGA = TRUE) 

#EGA NL
data_nl_net = data_nl %>% 
  select(p_income:ib_sex)

set.seed(1)
NL_ega = EGA(data=data_nl_net,  model = "glasso", 
                  plot.EGA = TRUE) 

#Indexes US
data_us = data_us %>% 
    mutate(index_1 = rowMeans(across(c(p_income, p_wealth, p_poor, p_black, b_diversity, b_equality))),
           index_2 = rowMeans(across(c(ib_race, ib_sex, ib_relig, ib_migra))),
           index_3 = rowMeans(across(c(b_merit, ib_work, ib_edu, ib_edupar,
                                       ib_weafam, ib_people))))

#Indexes NL
data_nl = data_nl %>% 
    mutate(index_1 = rowMeans(across(c(p_income, p_wealth, p_poor, p_black, b_diversity, b_equality, b_merit))),
           index_2 = rowMeans(across(c(ib_race, ib_sex, ib_relig, ib_migra))),
           index_3 = rowMeans(across(c(ib_work, ib_edu, ib_edupar,
                                       ib_weafam, ib_people))))

#Cronbach US
index_1_us = data_us %>% 
  select(p_income, p_wealth, p_poor, p_black, b_diversity, b_equality)

index_2_us = data_us %>% 
  select(ib_race, ib_migra, ib_relig, ib_sex)

index_3_us = data_us %>% 
  select(b_merit, ib_weafam, ib_edu, ib_edupar, ib_work, ib_people)

a_us_1 = cronbach.alpha(index_1_us, CI=TRUE, standardized=TRUE) # 0.858
a_us_2 = cronbach.alpha(index_2_us, CI=TRUE, standardized=TRUE) # 0.738
a_us_3 = cronbach.alpha(index_3_us, CI=TRUE, standardized=TRUE) # 0.457

#Cronbach NL
index_1_nl = data_us %>% 
  select(p_income, p_wealth, p_poor, p_black, b_merit, b_diversity, b_equality)

index_2_nl = data_us %>% 
  select(ib_race, ib_migra, ib_relig, ib_sex)

index_3_nl = data_us %>% 
  select(ib_weafam, ib_edu, ib_edupar, ib_work, ib_people)

a_nl_1 = cronbach.alpha(index_1_nl, CI=TRUE, standardized=TRUE) # 0.760
a_nl_2 = cronbach.alpha(index_2_nl, CI=TRUE, standardized=TRUE) # 0.738
a_nl_3 = cronbach.alpha(index_3_nl, CI=TRUE, standardized=TRUE) # 0.512

#Gather alphas and save
alphas = tibble(Index = c("Index 1", "Index 2", "Index 3"),
                Alpha_US = round(c(a_us_1$alpha, a_us_2$alpha, a_us_3$alpha),3),
                Alpha_NL = round(c(a_nl_1$alpha, a_nl_2$alpha, a_nl_3$alpha),3))

#Save
save(alphas, file = here("Output",  "alphas.RData"))

```

```{r}
#Models

#US
m0_us_b = lm(att_redist ~ cca, data = data_us)
m1_us_b = lm(att_redist ~ index_1 + index_2 + index_3 + sex + agegroups + immigrant + race + 
                education + working + hhincome_groups + marital + 
                politics + religion, data = data_us)
m2_us_b = lm(att_redist ~ index_1 + index_2 + index_3 + cca + sex + agegroups + immigrant + race + 
                education + working + hhincome_groups + marital + 
                politics + religion, data = data_us)

#NL
m0_nl_b = lm(att_redist ~ cca, data = data_nl)
m1_nl_b = lm(att_redist ~ index_1 + index_2 + index_3 + sex + agegroups + immigrant + race + 
                education + working + hhincome_groups + marital + 
                politics + religion, data = data_nl)
m2_nl_b = lm(att_redist ~ index_1 + index_2 + index_3 + cca + sex + agegroups + immigrant + race + 
                education + working + hhincome_groups + marital + 
                politics + religion, data = data_nl)
```


```{r}

#Output
tab_model(list(m0_us_b, m1_us_b, m2_us_b), 
          #order.terms = c(1:5, 23, 6:22),
          show.p = TRUE,
          p.style = "stars",
          p.threshold = c(0.1, 0.05, 0.01),
          dv.labels = c("M1-US", "M2-US", "M3-US"),
          collapse.ci = TRUE,
          show.aic = TRUE,
          #show.reflvl = TRUE,
          title = "Table. Linear regression models on attitude towards redistribution - US & NL",
          string.pred = " ",
          auto.label = FALSE, 
          file = here("Output", "Article", "Tables", "Attitude_Redistribution_US.html")
)


tab_model(list(m0_nl_b, m1_nl_b, m2_nl_b), 
          #order.terms = c(1:5, 23, 6:22),
          show.p = TRUE,
          p.style = "stars",
          p.threshold = c(0.1, 0.05, 0.01),
          dv.labels = c("M1-NL", "M2-NL", "M3-NL"),
          collapse.ci = TRUE,
          show.aic = TRUE,
          #show.reflvl = TRUE,
          title = "Table. Linear regression models on attitude towards redistribution - US & NL",
          string.pred = " ",
          auto.label = FALSE, 
          file = here("Output", "Article", "Tables", "Attitude_Redistribution_NL.html")
)


```

## Stability (bootstrap)

```{r}
#US1

# Perform Bootstrap EGA
ega_us_1_boot <- bootEGA(
  data = cca_us_1,
  iter = 2000,
  seed = 1,
  EGA.type = "EGA",
  model = "glasso",
  ncores = 8)

#compare bootstrapped vs sample EGA
ega_us_1_boot_sample <- compare.EGA.plots(
  ega_us_1, ega_us_1_boot,
  labels = c("Empirical", "Bootstrap"),
  plot.args = list(plot.type = "qgraph",
                   vsize = 15, 
                   node.alpha = 0.8,
                   legend.position = "none", legend.size = NA,
                   edge.color = c("royalblue", "tomato")))

ggsave(here("Output", "Supplemental", "ega_us_1_boot_sample.png"), 
       ega_us_1_boot_sample$comparison.plot, height = 12, width = 12)

#stability of dimensions
ega_us_1_stability = dimensionStability(ega_us_1_boot)

ggsave(here("Output", "Supplemental", "ega_us_1_stability.png"), 
       ega_us_1_stability$item.stability$plot)

```

```{r}
#US2

# Perform Bootstrap EGA
ega_us_2_boot <- bootEGA(
  data = cca_us_2,
  iter = 2000,
  seed = 1,
  EGA.type = "EGA",
  model = "glasso",
  ncores = 8)

#compare bootstrapped vs sample EGA
ega_us_2_boot_sample <- compare.EGA.plots(
  ega_us_2, ega_us_2_boot,
  labels = c("Empirical", "Bootstrap"),
  plot.args = list(plot.type = "qgraph",
                   vsize = 15, 
                   node.alpha = 0.8,
                   legend.position = "none", legend.size = NA,
                   edge.color = c("royalblue", "tomato")))

ggsave(here("Output", "Supplemental", "ega_us_2_boot_sample.png"), 
       ega_us_2_boot_sample$comparison.plot, height = 12, width = 12)

#stability of dimensions
ega_us_2_stability = dimensionStability(ega_us_2_boot)

ggsave(here("Output", "Supplemental", "ega_us_2_stability.png"), 
       ega_us_2_stability$item.stability$plot)

#assess stability of number of dimensions
table(ega_us_2_boot$boot.ndim[,2])
```

```{r}
#NL1

# Perform Bootstrap EGA
ega_nl_1_boot <- bootEGA(
  data = cca_nl_1,
  iter = 2000,
  seed = 1,
  EGA.type = "EGA",
  model = "glasso",
  ncores = 8)

#compare bootstrapped vs sample EGA
ega_nl_1_boot_sample <- compare.EGA.plots(
  ega_nl_1, ega_nl_1_boot,
  labels = c("Empirical", "Bootstrap"),
  plot.args = list(plot.type = "qgraph",
                   vsize = 15, 
                   node.alpha = 0.8,
                   legend.position = "none", legend.size = NA,
                   edge.color = c("royalblue", "tomato")))

ggsave(here("Output", "Supplemental", "ega_nl_1_boot_sample.png"), 
       ega_nl_1_boot_sample$comparison.plot, height = 12, width = 12)

#stability of dimensions
ega_nl_1_stability = dimensionStability(ega_nl_1_boot)

ggsave(here("Output", "Supplemental", "ega_nl_1_stability.png"), 
       ega_nl_1_stability$item.stability$plot)
```

```{r}
#NL1

# Perform Bootstrap EGA
ega_nl_2_boot <- bootEGA(
  data = cca_nl_2,
  iter = 2000,
  seed = 1,
  EGA.type = "EGA",
  model = "glasso",
  ncores = 8)

#compare bootstrapped vs sample EGA
ega_nl_2_boot_sample <- compare.EGA.plots(
  ega_nl_2, ega_nl_2_boot,
  labels = c("Empirical", "Bootstrap"),
  plot.args = list(plot.type = "qgraph",
                   vsize = 15, 
                   node.alpha = 0.8,
                   legend.position = "none", legend.size = NA,
                   edge.color = c("royalblue", "tomato")))

ggsave(here("Output", "Supplemental", "ega_nl_2_boot_sample.png"), 
       ega_nl_2_boot_sample$comparison.plot, height = 12, width = 12)

#stability of dimensions
ega_nl_2_stability = dimensionStability(ega_nl_2_boot)

ggsave(here("Output", "Supplemental", "ega_nl_2_stability.png"), 
       ega_nl_2_stability$item.stability$plot)
```

```{r}
#US full sample

# Perform Bootstrap EGA
ega_us_full_boot <- bootEGA(
  data = data_us_net,
  iter = 2000,
  seed = 1,
  EGA.type = "EGA",
  model = "glasso",
  ncores = 8)

#compare bootstrapped vs sample EGA
ega_us_full_boot_sample <- compare.EGA.plots(
  US_ega, ega_us_full_boot,
  labels = c("Empirical", "Bootstrap"),
  plot.args = list(plot.type = "qgraph",
                   vsize = 15, 
                   node.alpha = 0.8,
                   legend.position = "none", legend.size = NA,
                   edge.color = c("royalblue", "tomato")))

ggsave(here("Output", "Supplemental", "ega_us_full_boot_sample.png"), 
       ega_us_full_boot_sample$comparison.plot, height = 12, width = 12)

#stability of dimensions
ega_us_full_stability = dimensionStability(ega_us_full_boot)

ggsave(here("Output", "Supplemental", "ega_us_full_stability.png"), 
       ega_us_full_stability$item.stability$plot)
```

```{r}
#NL full sample

# Perform Bootstrap EGA
ega_nl_full_boot <- bootEGA(
  data = data_nl_net,
  iter = 2000,
  seed = 1,
  EGA.type = "EGA",
  model = "glasso",
  ncores = 8)

#compare bootstrapped vs sample EGA
ega_nl_full_boot_sample <- compare.EGA.plots(
  NL_ega, ega_nl_full_boot,
  labels = c("Empirical", "Bootstrap"),
  plot.args = list(plot.type = "qgraph",
                   vsize = 15, 
                   node.alpha = 0.8,
                   legend.position = "none", legend.size = NA,
                   edge.color = c("royalblue", "tomato")))

ggsave(here("Output", "Supplemental", "ega_nl_full_boot_sample.png"), 
       ega_nl_full_boot_sample$comparison.plot, height = 12, width = 12)

#stability of dimensions
ega_nl_full_stability = dimensionStability(ega_nl_full_boot)

ggsave(here("Output", "Supplemental", "ega_nl_full_stability.png"), 
       ega_nl_full_stability$item.stability$plot)
```

